<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>XrmDefinitelyTyped.Tool</AssemblyName>
    <RootNamespace>XrmDefinitelyTyped.Tool</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <PackageId>XrmDefinitelyTyped.Tool</PackageId>
    <ToolCommandName>xdt</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DataverseConnection" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.*" />
    <PackageReference Include="System.CommandLine" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XrmDefinitelyTyped.Core\XrmDefinitelyTyped.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
