<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>XrmTyped.Shared</AssemblyName>
    <RootNamespace>XrmTyped.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.*" />
    <PackageReference Include="Scriban" Version="7.*" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\*.sbn" />
  </ItemGroup>

</Project>
