/**
 * Hand-rolled stand-ins for everything the pasted `Account` declaration references but that lives
 * in other parts of a full XrmDefinitelyTyped output: the option-set enums, `Account_Fixed`, and
 * the `_Select`/`_Filter`/... sets of every related entity.
 *
 * `WebEntity` is deliberately *not* stubbed — it comes from the package's ambient contract, which
 * is exactly what this project is here to verify.
 *
 * Generated by scratchpad/gen-stubs.mjs — the point is only that the Account file type-checks
 * against this package's ambient contract, so the stubs carry just enough members to be usable.
 */

declare const enum account_accountcategorycode {
  Default = 1,
}
declare const enum account_accountclassificationcode {
  Default = 1,
}
declare const enum account_accountratingcode {
  Default = 1,
}
declare const enum account_address1_addresstypecode {
  Default = 1,
}
declare const enum account_address1_freighttermscode {
  Default = 1,
}
declare const enum account_address1_shippingmethodcode {
  Default = 1,
}
declare const enum account_address2_addresstypecode {
  Default = 1,
}
declare const enum account_address2_freighttermscode {
  Default = 1,
}
declare const enum account_address2_shippingmethodcode {
  Default = 1,
}
declare const enum account_businesstypecode {
  Default = 1,
}
declare const enum account_customersizecode {
  Default = 1,
}
declare const enum account_customertypecode {
  Default = 1,
}
declare const enum account_industrycode {
  Default = 1,
}
declare const enum account_ownershipcode {
  Default = 1,
}
declare const enum account_paymenttermscode {
  Default = 1,
}
declare const enum account_preferredappointmentdaycode {
  Default = 1,
}
declare const enum account_preferredappointmenttimecode {
  Default = 1,
}
declare const enum account_preferredcontactmethodcode {
  Default = 1,
}
declare const enum account_shippingmethodcode {
  Default = 1,
}
declare const enum account_statecode {
  Default = 1,
}
declare const enum account_statuscode {
  Default = 1,
}
declare const enum account_territorycode {
  Default = 1,
}
declare const enum msys_accounttype {
  Default = 1,
}

declare namespace XDT {
  interface Account_Fixed {
    accountid: string;
    "@odata.etag": string;
  }
  interface ActivityParty_Select {
    name: WebAttribute<ActivityParty_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface ActivityParty_Filter {
    name: string;
  }
  interface ActivityParty_Expand {}
  interface ActivityParty_Fixed {
    "@odata.etag": string;
  }
  interface ActivityParty_FormattedResult {
    name_formatted?: string;
  }
  interface ActivityParty_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface ActivityPointer_Select {
    name: WebAttribute<ActivityPointer_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface ActivityPointer_Filter {
    name: string;
  }
  interface ActivityPointer_Expand {}
  interface ActivityPointer_Fixed {
    "@odata.etag": string;
  }
  interface ActivityPointer_FormattedResult {
    name_formatted?: string;
  }
  interface ActivityPointer_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface Annotation_Select {
    name: WebAttribute<Annotation_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface Annotation_Filter {
    name: string;
  }
  interface Annotation_Expand {}
  interface Annotation_Fixed {
    "@odata.etag": string;
  }
  interface Annotation_FormattedResult {
    name_formatted?: string;
  }
  interface Annotation_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface Appointment_Select {
    name: WebAttribute<Appointment_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface Appointment_Filter {
    name: string;
  }
  interface Appointment_Expand {}
  interface Appointment_Fixed {
    "@odata.etag": string;
  }
  interface Appointment_FormattedResult {
    name_formatted?: string;
  }
  interface Appointment_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface Connection_Select {
    name: WebAttribute<Connection_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface Connection_Filter {
    name: string;
  }
  interface Connection_Expand {}
  interface Connection_Fixed {
    "@odata.etag": string;
  }
  interface Connection_FormattedResult {
    name_formatted?: string;
  }
  interface Connection_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface Contact_Select {
    fullname: WebAttribute<Contact_Select, { fullname: string | null }, { fullname_formatted?: string }>;
    firstname: WebAttribute<Contact_Select, { firstname: string | null }, { firstname_formatted?: string }>;
    lastname: WebAttribute<Contact_Select, { lastname: string | null }, { lastname_formatted?: string }>;
    emailaddress1: WebAttribute<Contact_Select, { emailaddress1: string | null }, { emailaddress1_formatted?: string }>;
  }
  interface Contact_Filter {
    fullname: string;
    firstname: string;
    lastname: string;
    emailaddress1: string;
  }
  interface Contact_Expand {}
  interface Contact_Fixed {
    "@odata.etag": string;
  }
  interface Contact_FormattedResult {
    fullname_formatted?: string;
    firstname_formatted?: string;
    lastname_formatted?: string;
    emailaddress1_formatted?: string;
  }
  interface Contact_Result extends WebEntity {
    "@odata.etag": string;
    fullname?: string | null;
    firstname?: string | null;
    lastname?: string | null;
    emailaddress1?: string | null;
  }
  interface Email_Select {
    name: WebAttribute<Email_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface Email_Filter {
    name: string;
  }
  interface Email_Expand {}
  interface Email_Fixed {
    "@odata.etag": string;
  }
  interface Email_FormattedResult {
    name_formatted?: string;
  }
  interface Email_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface Mailbox_Select {
    name: WebAttribute<Mailbox_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface Mailbox_Filter {
    name: string;
  }
  interface Mailbox_Expand {}
  interface Mailbox_Fixed {
    "@odata.etag": string;
  }
  interface Mailbox_FormattedResult {
    name_formatted?: string;
  }
  interface Mailbox_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface PhoneCall_Select {
    name: WebAttribute<PhoneCall_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface PhoneCall_Filter {
    name: string;
  }
  interface PhoneCall_Expand {}
  interface PhoneCall_Fixed {
    "@odata.etag": string;
  }
  interface PhoneCall_FormattedResult {
    name_formatted?: string;
  }
  interface PhoneCall_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface SystemUser_Select {
    fullname: WebAttribute<SystemUser_Select, { fullname: string | null }, { fullname_formatted?: string }>;
    domainname: WebAttribute<SystemUser_Select, { domainname: string | null }, { domainname_formatted?: string }>;
  }
  interface SystemUser_Filter {
    fullname: string;
    domainname: string;
  }
  interface SystemUser_Expand {}
  interface SystemUser_Fixed {
    "@odata.etag": string;
  }
  interface SystemUser_FormattedResult {
    fullname_formatted?: string;
    domainname_formatted?: string;
  }
  interface SystemUser_Result extends WebEntity {
    "@odata.etag": string;
    fullname?: string | null;
    domainname?: string | null;
  }
  interface Task_Select {
    name: WebAttribute<Task_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface Task_Filter {
    name: string;
  }
  interface Task_Expand {}
  interface Task_Fixed {
    "@odata.etag": string;
  }
  interface Task_FormattedResult {
    name_formatted?: string;
  }
  interface Task_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface Team_Select {
    name: WebAttribute<Team_Select, { name: string | null }, { name_formatted?: string }>;
    teamid: WebAttribute<Team_Select, { teamid: string | null }, { teamid_formatted?: string }>;
  }
  interface Team_Filter {
    name: string;
    teamid: string;
  }
  interface Team_Expand {}
  interface Team_Fixed {
    "@odata.etag": string;
  }
  interface Team_FormattedResult {
    name_formatted?: string;
    teamid_formatted?: string;
  }
  interface Team_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
    teamid?: string | null;
  }
  interface msys_Agreement_Select {
    name: WebAttribute<msys_Agreement_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Agreement_Filter {
    name: string;
  }
  interface msys_Agreement_Expand {}
  interface msys_Agreement_Fixed {
    "@odata.etag": string;
  }
  interface msys_Agreement_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Agreement_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_AgreementConnection_Select {
    name: WebAttribute<msys_AgreementConnection_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_AgreementConnection_Filter {
    name: string;
  }
  interface msys_AgreementConnection_Expand {}
  interface msys_AgreementConnection_Fixed {
    "@odata.etag": string;
  }
  interface msys_AgreementConnection_FormattedResult {
    name_formatted?: string;
  }
  interface msys_AgreementConnection_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Answer_Select {
    name: WebAttribute<msys_Answer_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Answer_Filter {
    name: string;
  }
  interface msys_Answer_Expand {}
  interface msys_Answer_Fixed {
    "@odata.etag": string;
  }
  interface msys_Answer_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Answer_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_ArrearsCase_Select {
    name: WebAttribute<msys_ArrearsCase_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_ArrearsCase_Filter {
    name: string;
  }
  interface msys_ArrearsCase_Expand {}
  interface msys_ArrearsCase_Fixed {
    "@odata.etag": string;
  }
  interface msys_ArrearsCase_FormattedResult {
    name_formatted?: string;
  }
  interface msys_ArrearsCase_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Case_Select {
    name: WebAttribute<msys_Case_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Case_Filter {
    name: string;
  }
  interface msys_Case_Expand {}
  interface msys_Case_Fixed {
    "@odata.etag": string;
  }
  interface msys_Case_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Case_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_City_Select {
    name: WebAttribute<msys_City_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_City_Filter {
    name: string;
  }
  interface msys_City_Expand {}
  interface msys_City_Fixed {
    "@odata.etag": string;
  }
  interface msys_City_FormattedResult {
    name_formatted?: string;
  }
  interface msys_City_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Committee_Select {
    name: WebAttribute<msys_Committee_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Committee_Filter {
    name: string;
  }
  interface msys_Committee_Expand {}
  interface msys_Committee_Fixed {
    "@odata.etag": string;
  }
  interface msys_Committee_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Committee_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_CommitteeMember_Select {
    name: WebAttribute<msys_CommitteeMember_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_CommitteeMember_Filter {
    name: string;
  }
  interface msys_CommitteeMember_Expand {}
  interface msys_CommitteeMember_Fixed {
    "@odata.etag": string;
  }
  interface msys_CommitteeMember_FormattedResult {
    name_formatted?: string;
  }
  interface msys_CommitteeMember_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Configuration_Select {
    name: WebAttribute<msys_Configuration_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Configuration_Filter {
    name: string;
  }
  interface msys_Configuration_Expand {}
  interface msys_Configuration_Fixed {
    "@odata.etag": string;
  }
  interface msys_Configuration_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Configuration_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Country_Select {
    name: WebAttribute<msys_Country_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Country_Filter {
    name: string;
  }
  interface msys_Country_Expand {}
  interface msys_Country_Fixed {
    "@odata.etag": string;
  }
  interface msys_Country_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Country_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_CustomerDiscount_Select {
    name: WebAttribute<msys_CustomerDiscount_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_CustomerDiscount_Filter {
    name: string;
  }
  interface msys_CustomerDiscount_Expand {}
  interface msys_CustomerDiscount_Fixed {
    "@odata.etag": string;
  }
  interface msys_CustomerDiscount_FormattedResult {
    name_formatted?: string;
  }
  interface msys_CustomerDiscount_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_DebitorSettlement_Select {
    name: WebAttribute<msys_DebitorSettlement_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_DebitorSettlement_Filter {
    name: string;
  }
  interface msys_DebitorSettlement_Expand {}
  interface msys_DebitorSettlement_Fixed {
    "@odata.etag": string;
  }
  interface msys_DebitorSettlement_FormattedResult {
    name_formatted?: string;
  }
  interface msys_DebitorSettlement_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Education_Select {
    name: WebAttribute<msys_Education_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Education_Filter {
    name: string;
  }
  interface msys_Education_Expand {}
  interface msys_Education_Fixed {
    "@odata.etag": string;
  }
  interface msys_Education_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Education_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_EducationType_Select {
    name: WebAttribute<msys_EducationType_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_EducationType_Filter {
    name: string;
  }
  interface msys_EducationType_Expand {}
  interface msys_EducationType_Fixed {
    "@odata.etag": string;
  }
  interface msys_EducationType_FormattedResult {
    name_formatted?: string;
  }
  interface msys_EducationType_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_EmailTemplate_Select {
    name: WebAttribute<msys_EmailTemplate_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_EmailTemplate_Filter {
    name: string;
  }
  interface msys_EmailTemplate_Expand {}
  interface msys_EmailTemplate_Fixed {
    "@odata.etag": string;
  }
  interface msys_EmailTemplate_FormattedResult {
    name_formatted?: string;
  }
  interface msys_EmailTemplate_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Employment_Select {
    name: WebAttribute<msys_Employment_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Employment_Filter {
    name: string;
  }
  interface msys_Employment_Expand {}
  interface msys_Employment_Fixed {
    "@odata.etag": string;
  }
  interface msys_Employment_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Employment_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Event_Select {
    name: WebAttribute<msys_Event_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Event_Filter {
    name: string;
  }
  interface msys_Event_Expand {}
  interface msys_Event_Fixed {
    "@odata.etag": string;
  }
  interface msys_Event_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Event_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Financetype_Select {
    name: WebAttribute<msys_Financetype_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Financetype_Filter {
    name: string;
  }
  interface msys_Financetype_Expand {}
  interface msys_Financetype_Fixed {
    "@odata.etag": string;
  }
  interface msys_Financetype_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Financetype_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_InternalNote_Select {
    name: WebAttribute<msys_InternalNote_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_InternalNote_Filter {
    name: string;
  }
  interface msys_InternalNote_Expand {}
  interface msys_InternalNote_Fixed {
    "@odata.etag": string;
  }
  interface msys_InternalNote_FormattedResult {
    name_formatted?: string;
  }
  interface msys_InternalNote_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Invoice_Select {
    name: WebAttribute<msys_Invoice_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Invoice_Filter {
    name: string;
  }
  interface msys_Invoice_Expand {}
  interface msys_Invoice_Fixed {
    "@odata.etag": string;
  }
  interface msys_Invoice_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Invoice_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_InvoiceDivision_Select {
    name: WebAttribute<msys_InvoiceDivision_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_InvoiceDivision_Filter {
    name: string;
  }
  interface msys_InvoiceDivision_Expand {}
  interface msys_InvoiceDivision_Fixed {
    "@odata.etag": string;
  }
  interface msys_InvoiceDivision_FormattedResult {
    name_formatted?: string;
  }
  interface msys_InvoiceDivision_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Membership_Select {
    name: WebAttribute<msys_Membership_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Membership_Filter {
    name: string;
  }
  interface msys_Membership_Expand {}
  interface msys_Membership_Fixed {
    "@odata.etag": string;
  }
  interface msys_Membership_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Membership_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Municipality_Select {
    name: WebAttribute<msys_Municipality_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Municipality_Filter {
    name: string;
  }
  interface msys_Municipality_Expand {}
  interface msys_Municipality_Fixed {
    "@odata.etag": string;
  }
  interface msys_Municipality_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Municipality_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Payment_Select {
    name: WebAttribute<msys_Payment_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Payment_Filter {
    name: string;
  }
  interface msys_Payment_Expand {}
  interface msys_Payment_Fixed {
    "@odata.etag": string;
  }
  interface msys_Payment_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Payment_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_PaymentMethod_Select {
    name: WebAttribute<msys_PaymentMethod_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_PaymentMethod_Filter {
    name: string;
  }
  interface msys_PaymentMethod_Expand {}
  interface msys_PaymentMethod_Fixed {
    "@odata.etag": string;
  }
  interface msys_PaymentMethod_FormattedResult {
    name_formatted?: string;
  }
  interface msys_PaymentMethod_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_PayrollRun_Select {
    name: WebAttribute<msys_PayrollRun_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_PayrollRun_Filter {
    name: string;
  }
  interface msys_PayrollRun_Expand {}
  interface msys_PayrollRun_Fixed {
    "@odata.etag": string;
  }
  interface msys_PayrollRun_FormattedResult {
    name_formatted?: string;
  }
  interface msys_PayrollRun_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_PlacementRule_Select {
    name: WebAttribute<msys_PlacementRule_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_PlacementRule_Filter {
    name: string;
  }
  interface msys_PlacementRule_Expand {}
  interface msys_PlacementRule_Fixed {
    "@odata.etag": string;
  }
  interface msys_PlacementRule_FormattedResult {
    name_formatted?: string;
  }
  interface msys_PlacementRule_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_PostalCode_Select {
    name: WebAttribute<msys_PostalCode_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_PostalCode_Filter {
    name: string;
  }
  interface msys_PostalCode_Expand {}
  interface msys_PostalCode_Fixed {
    "@odata.etag": string;
  }
  interface msys_PostalCode_FormattedResult {
    name_formatted?: string;
  }
  interface msys_PostalCode_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Product_Select {
    name: WebAttribute<msys_Product_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Product_Filter {
    name: string;
  }
  interface msys_Product_Expand {}
  interface msys_Product_Fixed {
    "@odata.etag": string;
  }
  interface msys_Product_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Product_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Region_Select {
    name: WebAttribute<msys_Region_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Region_Filter {
    name: string;
  }
  interface msys_Region_Expand {}
  interface msys_Region_Fixed {
    "@odata.etag": string;
  }
  interface msys_Region_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Region_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Registration_Select {
    name: WebAttribute<msys_Registration_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Registration_Filter {
    name: string;
  }
  interface msys_Registration_Expand {}
  interface msys_Registration_Fixed {
    "@odata.etag": string;
  }
  interface msys_Registration_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Registration_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_SelfServiceRights_Select {
    name: WebAttribute<msys_SelfServiceRights_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_SelfServiceRights_Filter {
    name: string;
  }
  interface msys_SelfServiceRights_Expand {}
  interface msys_SelfServiceRights_Fixed {
    "@odata.etag": string;
  }
  interface msys_SelfServiceRights_FormattedResult {
    name_formatted?: string;
  }
  interface msys_SelfServiceRights_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_TaxReport_Select {
    name: WebAttribute<msys_TaxReport_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_TaxReport_Filter {
    name: string;
  }
  interface msys_TaxReport_Expand {}
  interface msys_TaxReport_Fixed {
    "@odata.etag": string;
  }
  interface msys_TaxReport_FormattedResult {
    name_formatted?: string;
  }
  interface msys_TaxReport_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_Transaction_Select {
    name: WebAttribute<msys_Transaction_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_Transaction_Filter {
    name: string;
  }
  interface msys_Transaction_Expand {}
  interface msys_Transaction_Fixed {
    "@odata.etag": string;
  }
  interface msys_Transaction_FormattedResult {
    name_formatted?: string;
  }
  interface msys_Transaction_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
  interface msys_WorkplaceType_Select {
    name: WebAttribute<msys_WorkplaceType_Select, { name: string | null }, { name_formatted?: string }>;
  }
  interface msys_WorkplaceType_Filter {
    name: string;
  }
  interface msys_WorkplaceType_Expand {}
  interface msys_WorkplaceType_Fixed {
    "@odata.etag": string;
  }
  interface msys_WorkplaceType_FormattedResult {
    name_formatted?: string;
  }
  interface msys_WorkplaceType_Result extends WebEntity {
    "@odata.etag": string;
    name?: string | null;
  }
}
