/**
 * Real XrmDefinitelyTyped output, pasted verbatim (Account only).
 *
 * Everything Account references but that lives elsewhere in the generated file — `WebEntity`,
 * `Account_Fixed`, the option-set types and the other entities' `_Select`/`_Filter`/… interfaces —
 * is stubbed in `stubs.d.ts`.
 */

declare namespace XDT {
  interface Account_Base extends WebEntity {
    accountcategorycode?: account_accountcategorycode | null;
    accountclassificationcode?: account_accountclassificationcode | null;
    accountid?: string | null;
    accountnumber?: string | null;
    accountratingcode?: account_accountratingcode | null;
    address1_addressid?: string | null;
    address1_addresstypecode?: account_address1_addresstypecode | null;
    address1_city?: string | null;
    address1_composite?: string | null;
    address1_country?: string | null;
    address1_county?: string | null;
    address1_fax?: string | null;
    address1_freighttermscode?: account_address1_freighttermscode | null;
    address1_latitude?: number | null;
    address1_line1?: string | null;
    address1_line2?: string | null;
    address1_line3?: string | null;
    address1_longitude?: number | null;
    address1_name?: string | null;
    address1_postalcode?: string | null;
    address1_postofficebox?: string | null;
    address1_primarycontactname?: string | null;
    address1_shippingmethodcode?: account_address1_shippingmethodcode | null;
    address1_stateorprovince?: string | null;
    address1_telephone1?: string | null;
    address1_telephone2?: string | null;
    address1_telephone3?: string | null;
    address1_upszone?: string | null;
    address1_utcoffset?: number | null;
    address2_addressid?: string | null;
    address2_addresstypecode?: account_address2_addresstypecode | null;
    address2_city?: string | null;
    address2_composite?: string | null;
    address2_country?: string | null;
    address2_county?: string | null;
    address2_fax?: string | null;
    address2_freighttermscode?: account_address2_freighttermscode | null;
    address2_latitude?: number | null;
    address2_line1?: string | null;
    address2_line2?: string | null;
    address2_line3?: string | null;
    address2_longitude?: number | null;
    address2_name?: string | null;
    address2_postalcode?: string | null;
    address2_postofficebox?: string | null;
    address2_primarycontactname?: string | null;
    address2_shippingmethodcode?: account_address2_shippingmethodcode | null;
    address2_stateorprovince?: string | null;
    address2_telephone1?: string | null;
    address2_telephone2?: string | null;
    address2_telephone3?: string | null;
    address2_upszone?: string | null;
    address2_utcoffset?: number | null;
    adx_createdbyipaddress?: string | null;
    adx_createdbyusername?: string | null;
    adx_modifiedbyipaddress?: string | null;
    adx_modifiedbyusername?: string | null;
    aging30?: number | null;
    aging30_base?: number | null;
    aging60?: number | null;
    aging60_base?: number | null;
    aging90?: number | null;
    aging90_base?: number | null;
    businesstypecode?: account_businesstypecode | null;
    createdon?: Date | null;
    creditlimit?: number | null;
    creditlimit_base?: number | null;
    creditonhold?: boolean | null;
    customersizecode?: account_customersizecode | null;
    customertypecode?: account_customertypecode | null;
    description?: string | null;
    donotbulkemail?: boolean | null;
    donotbulkpostalmail?: boolean | null;
    donotemail?: boolean | null;
    donotfax?: boolean | null;
    donotphone?: boolean | null;
    donotpostalmail?: boolean | null;
    donotsendmm?: boolean | null;
    emailaddress1?: string | null;
    emailaddress2?: string | null;
    emailaddress3?: string | null;
    entityimageid?: string | null;
    exchangerate?: number | null;
    fax?: string | null;
    followemail?: boolean | null;
    ftpsiteurl?: string | null;
    importsequencenumber?: number | null;
    industrycode?: account_industrycode | null;
    isprivate?: boolean | null;
    lastonholdtime?: Date | null;
    lastusedincampaign?: Date | null;
    marketcap?: number | null;
    marketcap_base?: number | null;
    marketingonly?: boolean | null;
    merged?: boolean | null;
    modifiedon?: Date | null;
    msys_accountnumber?: string | null;
    msys_accounttype?: msys_accounttype | null;
    msys_accountvalidated?: boolean | null;
    msys_address1floor?: string | null;
    msys_address1houseletter?: string | null;
    msys_address1housenumber?: string | null;
    msys_address1locationonfloor?: string | null;
    msys_address1streetname?: string | null;
    msys_combinedaddress?: string | null;
    msys_constitutiondayisdayoff?: boolean | null;
    msys_cvrnum?: string | null;
    msys_debtor?: boolean | null;
    msys_erpaccount?: string | null;
    msys_erpcompanycode?: string | null;
    msys_erpcostlocation?: string | null;
    msys_erptype?: string | null;
    msys_eventcancellationreceipt?: string | null;
    msys_eventsignupreceipt?: string | null;
    msys_extid?: string | null;
    msys_hideonselfservice?: boolean | null;
    msys_invoicingblocked?: boolean | null;
    msys_nocvrnum?: boolean | null;
    msys_offerspayrollpayment?: boolean | null;
    msys_pictureid?: string | null;
    msys_placeofeducation?: boolean | null;
    msys_postalcodemissing?: boolean | null;
    msys_publicavailable?: boolean | null;
    msys_shouldcreateexternaleventpostings?: boolean | null;
    msys_uvmnum?: string | null;
    name?: string | null;
    numberofemployees?: number | null;
    onholdtime?: number | null;
    overriddencreatedon?: Date | null;
    ownershipcode?: account_ownershipcode | null;
    participatesinworkflow?: boolean | null;
    paymenttermscode?: account_paymenttermscode | null;
    preferredappointmentdaycode?: account_preferredappointmentdaycode | null;
    preferredappointmenttimecode?: account_preferredappointmenttimecode | null;
    preferredcontactmethodcode?: account_preferredcontactmethodcode | null;
    primarysatoriid?: string | null;
    primarytwitterid?: string | null;
    processid?: string | null;
    revenue?: number | null;
    revenue_base?: number | null;
    sharesoutstanding?: number | null;
    shippingmethodcode?: account_shippingmethodcode | null;
    sic?: string | null;
    stageid?: string | null;
    statecode?: account_statecode | null;
    statuscode?: account_statuscode | null;
    stockexchange?: string | null;
    telephone1?: string | null;
    telephone2?: string | null;
    telephone3?: string | null;
    territorycode?: account_territorycode | null;
    tickersymbol?: string | null;
    timespentbymeonemailandmeetings?: string | null;
    timezoneruleversionnumber?: number | null;
    transactioncurrencyid_guid?: string | null;
    traversedpath?: string | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
    websiteurl?: string | null;
  }
  interface Account_Relationships {
    Account_ActivityPointers?: ActivityPointer_Result[] | null;
    Account_Annotation?: Annotation_Result[] | null;
    Account_Appointments?: Appointment_Result[] | null;
    Account_Email_EmailSender?: Email_Result[] | null;
    Account_Email_SendersAccount?: Email_Result[] | null;
    Account_Emails?: Email_Result[] | null;
    Account_Phonecalls?: PhoneCall_Result[] | null;
    Account_Tasks?: Task_Result[] | null;
    account_activity_parties?: ActivityParty_Result[] | null;
    account_connections1?: Connection_Result[] | null;
    account_connections2?: Connection_Result[] | null;
    account_master_account?: Account_Result[] | null;
    account_msys_InternalNotes?: msys_InternalNote_Result[] | null;
    account_parent_account?: Account_Result[] | null;
    contact_customer_accounts?: Contact_Result[] | null;
    msa_account_managingpartner?: Account_Result[] | null;
    msa_contact_managingpartner?: Contact_Result[] | null;
    msys_Account_msys_CommitteeMember_msys_CommitteeMember?: msys_CommitteeMember_Result[] | null;
    msys_Address1City?: msys_City_Result | null;
    msys_Address1Country?: msys_Country_Result | null;
    msys_Address1Municipality?: msys_Municipality_Result | null;
    msys_Address1PostalCode?: msys_PostalCode_Result | null;
    msys_Address1_Region?: msys_Region_Result | null;
    msys_ArrearsCase?: msys_ArrearsCase_Result | null;
    msys_AssociationCommitteemembership?: Account_Result | null;
    msys_Case_Account_AdditionalParties?: msys_Case_Result[] | null;
    msys_EmailTemplateEventCancellationReceipt?: msys_EmailTemplate_Result | null;
    msys_EmailTemplateEventSignupReceipt?: msys_EmailTemplate_Result | null;
    msys_EmailTemplateEventSignupReceiptPhysical?: msys_EmailTemplate_Result | null;
    msys_EmailTemplateEventSignupReceiptVirtual?: msys_EmailTemplate_Result | null;
    msys_EmailTemplateEventSignupWaitlist?: msys_EmailTemplate_Result | null;
    msys_EmailTemplateEventWaitingListOffer?: msys_EmailTemplate_Result | null;
    msys_EmailTemplateEventWaitingListPromotion?: msys_EmailTemplate_Result | null;
    msys_EmailTemplateWaitListPromotionPhysical?: msys_EmailTemplate_Result | null;
    msys_EmailTemplateWaitListPromotionVirtual?: msys_EmailTemplate_Result | null;
    msys_MailboxForSendingEmails?: Mailbox_Result | null;
    msys_PrimaryPaymentMethod?: msys_PaymentMethod_Result | null;
    msys_SubUnion?: Team_Result | null;
    msys_TopMainCompany?: Account_Result | null;
    msys_WorkplaceType?: msys_WorkplaceType_Result | null;
    msys_account_AssociationCommitteemembership_account?: Account_Result[] | null;
    msys_account_TopMainCompany_account?: Account_Result[] | null;
    msys_account_msys_arrearscase_656?: msys_ArrearsCase_Result[] | null;
    msys_account_msys_case?: msys_Case_Result[] | null;
    msys_account_msys_case_primary_party?: msys_Case_Result[] | null;
    msys_account_msys_customerdiscount_51?: msys_CustomerDiscount_Result[] | null;
    msys_account_msys_invoice_928?: msys_Invoice_Result[] | null;
    msys_account_msys_invoicedivision_313?: msys_InvoiceDivision_Result[] | null;
    msys_account_msys_membership_549?: msys_Membership_Result[] | null;
    msys_account_msys_payment_960?: msys_Payment_Result[] | null;
    msys_account_msys_paymentmethod_452?: msys_PaymentMethod_Result[] | null;
    msys_account_msys_selfservicerights_48?: msys_SelfServiceRights_Result[] | null;
    msys_account_msys_taxreport_639?: msys_TaxReport_Result[] | null;
    msys_account_msys_transaction_933?: msys_Transaction_Result[] | null;
    msys_agreement_Account_account?: msys_Agreement_Result[] | null;
    msys_agreementconnection_Account_account?: msys_AgreementConnection_Result[] | null;
    msys_committee_AccountUnion_account?: msys_Committee_Result[] | null;
    msys_committeemember_AccountAppointedBy_account?: msys_CommitteeMember_Result[] | null;
    msys_configuration_MainUnion_account?: msys_Configuration_Result[] | null;
    msys_contact_PrimaryWorkplace_account?: Contact_Result[] | null;
    msys_contact_SecondaryUnion_account?: Contact_Result[] | null;
    msys_debitorsettlement_Account_account?: msys_DebitorSettlement_Result[] | null;
    msys_education_PlaceOfEducation_account?: msys_Education_Result[] | null;
    msys_educationtype_PlaceOfStudy_account?: msys_EducationType_Result[] | null;
    msys_employment_Workplace_account?: msys_Employment_Result[] | null;
    msys_event_Organizer_account?: msys_Event_Result[] | null;
    msys_event_Venue_account?: msys_Event_Result[] | null;
    msys_financetype_Account_account?: msys_Financetype_Result[] | null;
    msys_msys_answer_account_msys_DynamicListAnswer?: msys_Answer_Result[] | null;
    msys_msys_emailtemplate_account_msys_ValidationEntity?: msys_EmailTemplate_Result[] | null;
    msys_paymentmethod_PayrollAt_account?: msys_PaymentMethod_Result[] | null;
    msys_payrollrun_Account_account?: msys_PayrollRun_Result[] | null;
    msys_placementrule_Account_account?: msys_PlacementRule_Result[] | null;
    msys_product_Related_Account_account?: msys_Product_Result[] | null;
    msys_registration_CompanyPayer_account?: msys_Registration_Result[] | null;
    msys_team_SubUnion_account?: Team_Result[] | null;
    msys_team_TopLevelWorkplace_account?: Team_Result[] | null;
  }
  interface Account extends Account_Base, Account_Relationships {
    msa_managingpartnerid_bind$accounts?: string | null;
    msys_Address1City_bind$msys_cities?: string | null;
    msys_Address1Country_bind$msys_countries?: string | null;
    msys_Address1Municipality_bind$msys_municipalities?: string | null;
    msys_Address1PostalCode_bind$msys_postalcodes?: string | null;
    msys_Address1_Region_bind$msys_regions?: string | null;
    msys_ArrearsCase_bind$msys_arrearscases?: string | null;
    msys_AssociationCommitteemembership_bind$accounts?: string | null;
    msys_EmailTemplateEventCancellationReceipt_bind$msys_emailtemplates?: string | null;
    msys_EmailTemplateEventSignupReceiptPhysical_bind$msys_emailtemplates?: string | null;
    msys_EmailTemplateEventSignupReceiptVirtual_bind$msys_emailtemplates?: string | null;
    msys_EmailTemplateEventSignupReceipt_bind$msys_emailtemplates?: string | null;
    msys_EmailTemplateEventSignupWaitlist_bind$msys_emailtemplates?: string | null;
    msys_EmailTemplateEventWaitingListOffer_bind$msys_emailtemplates?: string | null;
    msys_EmailTemplateEventWaitingListPromotion_bind$msys_emailtemplates?: string | null;
    msys_EmailTemplateWaitListPromotionPhysical_bind$msys_emailtemplates?: string | null;
    msys_EmailTemplateWaitListPromotionVirtual_bind$msys_emailtemplates?: string | null;
    msys_MailboxForSendingEmails_bind$mailboxes?: string | null;
    msys_PrimaryPaymentMethod_bind$msys_paymentmethods?: string | null;
    msys_SubUnion_bind$teams?: string | null;
    msys_TopMainCompany_bind$accounts?: string | null;
    msys_WorkplaceType_bind$msys_workplacetypes?: string | null;
    ownerid_bind$systemusers?: string | null;
    ownerid_bind$teams?: string | null;
    parentaccountid_bind$accounts?: string | null;
    preferredsystemuserid_bind$systemusers?: string | null;
    primarycontactid_bind$contacts?: string | null;
    sla_account_sla_bind$slas?: string | null;
    stageid_processstage_bind$processstages?: string | null;
    transactioncurrencyid_bind$transactioncurrencies?: string | null;
  }
  interface Account_Create extends Account {}
  interface Account_Update extends Account {}
  interface Account_Select {
    accountcategorycode: WebAttribute<Account_Select, { accountcategorycode: account_accountcategorycode | null }, { accountcategorycode_formatted?: string }>;
    accountclassificationcode: WebAttribute<Account_Select, { accountclassificationcode: account_accountclassificationcode | null }, { accountclassificationcode_formatted?: string }>;
    accountid: WebAttribute<Account_Select, { accountid: string | null }, {  }>;
    accountnumber: WebAttribute<Account_Select, { accountnumber: string | null }, {  }>;
    accountratingcode: WebAttribute<Account_Select, { accountratingcode: account_accountratingcode | null }, { accountratingcode_formatted?: string }>;
    address1_addressid: WebAttribute<Account_Select, { address1_addressid: string | null }, {  }>;
    address1_addresstypecode: WebAttribute<Account_Select, { address1_addresstypecode: account_address1_addresstypecode | null }, { address1_addresstypecode_formatted?: string }>;
    address1_city: WebAttribute<Account_Select, { address1_city: string | null }, {  }>;
    address1_composite: WebAttribute<Account_Select, { address1_composite: string | null }, {  }>;
    address1_country: WebAttribute<Account_Select, { address1_country: string | null }, {  }>;
    address1_county: WebAttribute<Account_Select, { address1_county: string | null }, {  }>;
    address1_fax: WebAttribute<Account_Select, { address1_fax: string | null }, {  }>;
    address1_freighttermscode: WebAttribute<Account_Select, { address1_freighttermscode: account_address1_freighttermscode | null }, { address1_freighttermscode_formatted?: string }>;
    address1_latitude: WebAttribute<Account_Select, { address1_latitude: number | null }, {  }>;
    address1_line1: WebAttribute<Account_Select, { address1_line1: string | null }, {  }>;
    address1_line2: WebAttribute<Account_Select, { address1_line2: string | null }, {  }>;
    address1_line3: WebAttribute<Account_Select, { address1_line3: string | null }, {  }>;
    address1_longitude: WebAttribute<Account_Select, { address1_longitude: number | null }, {  }>;
    address1_name: WebAttribute<Account_Select, { address1_name: string | null }, {  }>;
    address1_postalcode: WebAttribute<Account_Select, { address1_postalcode: string | null }, {  }>;
    address1_postofficebox: WebAttribute<Account_Select, { address1_postofficebox: string | null }, {  }>;
    address1_primarycontactname: WebAttribute<Account_Select, { address1_primarycontactname: string | null }, {  }>;
    address1_shippingmethodcode: WebAttribute<Account_Select, { address1_shippingmethodcode: account_address1_shippingmethodcode | null }, { address1_shippingmethodcode_formatted?: string }>;
    address1_stateorprovince: WebAttribute<Account_Select, { address1_stateorprovince: string | null }, {  }>;
    address1_telephone1: WebAttribute<Account_Select, { address1_telephone1: string | null }, {  }>;
    address1_telephone2: WebAttribute<Account_Select, { address1_telephone2: string | null }, {  }>;
    address1_telephone3: WebAttribute<Account_Select, { address1_telephone3: string | null }, {  }>;
    address1_upszone: WebAttribute<Account_Select, { address1_upszone: string | null }, {  }>;
    address1_utcoffset: WebAttribute<Account_Select, { address1_utcoffset: number | null }, {  }>;
    address2_addressid: WebAttribute<Account_Select, { address2_addressid: string | null }, {  }>;
    address2_addresstypecode: WebAttribute<Account_Select, { address2_addresstypecode: account_address2_addresstypecode | null }, { address2_addresstypecode_formatted?: string }>;
    address2_city: WebAttribute<Account_Select, { address2_city: string | null }, {  }>;
    address2_composite: WebAttribute<Account_Select, { address2_composite: string | null }, {  }>;
    address2_country: WebAttribute<Account_Select, { address2_country: string | null }, {  }>;
    address2_county: WebAttribute<Account_Select, { address2_county: string | null }, {  }>;
    address2_fax: WebAttribute<Account_Select, { address2_fax: string | null }, {  }>;
    address2_freighttermscode: WebAttribute<Account_Select, { address2_freighttermscode: account_address2_freighttermscode | null }, { address2_freighttermscode_formatted?: string }>;
    address2_latitude: WebAttribute<Account_Select, { address2_latitude: number | null }, {  }>;
    address2_line1: WebAttribute<Account_Select, { address2_line1: string | null }, {  }>;
    address2_line2: WebAttribute<Account_Select, { address2_line2: string | null }, {  }>;
    address2_line3: WebAttribute<Account_Select, { address2_line3: string | null }, {  }>;
    address2_longitude: WebAttribute<Account_Select, { address2_longitude: number | null }, {  }>;
    address2_name: WebAttribute<Account_Select, { address2_name: string | null }, {  }>;
    address2_postalcode: WebAttribute<Account_Select, { address2_postalcode: string | null }, {  }>;
    address2_postofficebox: WebAttribute<Account_Select, { address2_postofficebox: string | null }, {  }>;
    address2_primarycontactname: WebAttribute<Account_Select, { address2_primarycontactname: string | null }, {  }>;
    address2_shippingmethodcode: WebAttribute<Account_Select, { address2_shippingmethodcode: account_address2_shippingmethodcode | null }, { address2_shippingmethodcode_formatted?: string }>;
    address2_stateorprovince: WebAttribute<Account_Select, { address2_stateorprovince: string | null }, {  }>;
    address2_telephone1: WebAttribute<Account_Select, { address2_telephone1: string | null }, {  }>;
    address2_telephone2: WebAttribute<Account_Select, { address2_telephone2: string | null }, {  }>;
    address2_telephone3: WebAttribute<Account_Select, { address2_telephone3: string | null }, {  }>;
    address2_upszone: WebAttribute<Account_Select, { address2_upszone: string | null }, {  }>;
    address2_utcoffset: WebAttribute<Account_Select, { address2_utcoffset: number | null }, {  }>;
    adx_createdbyipaddress: WebAttribute<Account_Select, { adx_createdbyipaddress: string | null }, {  }>;
    adx_createdbyusername: WebAttribute<Account_Select, { adx_createdbyusername: string | null }, {  }>;
    adx_modifiedbyipaddress: WebAttribute<Account_Select, { adx_modifiedbyipaddress: string | null }, {  }>;
    adx_modifiedbyusername: WebAttribute<Account_Select, { adx_modifiedbyusername: string | null }, {  }>;
    aging30: WebAttribute<Account_Select, { aging30: number | null; transactioncurrencyid_guid: string | null }, { aging30_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging30_base: WebAttribute<Account_Select, { aging30_base: number | null; transactioncurrencyid_guid: string | null }, { aging30_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging60: WebAttribute<Account_Select, { aging60: number | null; transactioncurrencyid_guid: string | null }, { aging60_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging60_base: WebAttribute<Account_Select, { aging60_base: number | null; transactioncurrencyid_guid: string | null }, { aging60_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging90: WebAttribute<Account_Select, { aging90: number | null; transactioncurrencyid_guid: string | null }, { aging90_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging90_base: WebAttribute<Account_Select, { aging90_base: number | null; transactioncurrencyid_guid: string | null }, { aging90_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    businesstypecode: WebAttribute<Account_Select, { businesstypecode: account_businesstypecode | null }, { businesstypecode_formatted?: string }>;
    createdby_guid: WebAttribute<Account_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdbyexternalparty_guid: WebAttribute<Account_Select, { createdbyexternalparty_guid: string | null }, { createdbyexternalparty_formatted?: string }>;
    createdon: WebAttribute<Account_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<Account_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    creditlimit: WebAttribute<Account_Select, { creditlimit: number | null; transactioncurrencyid_guid: string | null }, { creditlimit_formatted?: string; transactioncurrencyid_formatted?: string }>;
    creditlimit_base: WebAttribute<Account_Select, { creditlimit_base: number | null; transactioncurrencyid_guid: string | null }, { creditlimit_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    creditonhold: WebAttribute<Account_Select, { creditonhold: boolean | null }, {  }>;
    customersizecode: WebAttribute<Account_Select, { customersizecode: account_customersizecode | null }, { customersizecode_formatted?: string }>;
    customertypecode: WebAttribute<Account_Select, { customertypecode: account_customertypecode | null }, { customertypecode_formatted?: string }>;
    description: WebAttribute<Account_Select, { description: string | null }, {  }>;
    donotbulkemail: WebAttribute<Account_Select, { donotbulkemail: boolean | null }, {  }>;
    donotbulkpostalmail: WebAttribute<Account_Select, { donotbulkpostalmail: boolean | null }, {  }>;
    donotemail: WebAttribute<Account_Select, { donotemail: boolean | null }, {  }>;
    donotfax: WebAttribute<Account_Select, { donotfax: boolean | null }, {  }>;
    donotphone: WebAttribute<Account_Select, { donotphone: boolean | null }, {  }>;
    donotpostalmail: WebAttribute<Account_Select, { donotpostalmail: boolean | null }, {  }>;
    donotsendmm: WebAttribute<Account_Select, { donotsendmm: boolean | null }, {  }>;
    emailaddress1: WebAttribute<Account_Select, { emailaddress1: string | null }, {  }>;
    emailaddress2: WebAttribute<Account_Select, { emailaddress2: string | null }, {  }>;
    emailaddress3: WebAttribute<Account_Select, { emailaddress3: string | null }, {  }>;
    entityimageid: WebAttribute<Account_Select, { entityimageid: string | null }, {  }>;
    exchangerate: WebAttribute<Account_Select, { exchangerate: number | null }, {  }>;
    fax: WebAttribute<Account_Select, { fax: string | null }, {  }>;
    followemail: WebAttribute<Account_Select, { followemail: boolean | null }, {  }>;
    ftpsiteurl: WebAttribute<Account_Select, { ftpsiteurl: string | null }, {  }>;
    importsequencenumber: WebAttribute<Account_Select, { importsequencenumber: number | null }, {  }>;
    industrycode: WebAttribute<Account_Select, { industrycode: account_industrycode | null }, { industrycode_formatted?: string }>;
    isprivate: WebAttribute<Account_Select, { isprivate: boolean | null }, {  }>;
    lastonholdtime: WebAttribute<Account_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
    lastusedincampaign: WebAttribute<Account_Select, { lastusedincampaign: Date | null }, { lastusedincampaign_formatted?: string }>;
    marketcap: WebAttribute<Account_Select, { marketcap: number | null; transactioncurrencyid_guid: string | null }, { marketcap_formatted?: string; transactioncurrencyid_formatted?: string }>;
    marketcap_base: WebAttribute<Account_Select, { marketcap_base: number | null; transactioncurrencyid_guid: string | null }, { marketcap_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    marketingonly: WebAttribute<Account_Select, { marketingonly: boolean | null }, {  }>;
    masterid_guid: WebAttribute<Account_Select, { masterid_guid: string | null }, { masterid_formatted?: string }>;
    merged: WebAttribute<Account_Select, { merged: boolean | null }, {  }>;
    modifiedby_guid: WebAttribute<Account_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedbyexternalparty_guid: WebAttribute<Account_Select, { modifiedbyexternalparty_guid: string | null }, { modifiedbyexternalparty_formatted?: string }>;
    modifiedon: WebAttribute<Account_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<Account_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    msa_managingpartnerid_guid: WebAttribute<Account_Select, { msa_managingpartnerid_guid: string | null }, { msa_managingpartnerid_formatted?: string }>;
    msys_accountnumber: WebAttribute<Account_Select, { msys_accountnumber: string | null }, {  }>;
    msys_accounttype: WebAttribute<Account_Select, { msys_accounttype: msys_accounttype | null }, { msys_accounttype_formatted?: string }>;
    msys_accountvalidated: WebAttribute<Account_Select, { msys_accountvalidated: boolean | null }, {  }>;
    msys_address1_region_guid: WebAttribute<Account_Select, { msys_address1_region_guid: string | null }, { msys_address1_region_formatted?: string }>;
    msys_address1city_guid: WebAttribute<Account_Select, { msys_address1city_guid: string | null }, { msys_address1city_formatted?: string }>;
    msys_address1country_guid: WebAttribute<Account_Select, { msys_address1country_guid: string | null }, { msys_address1country_formatted?: string }>;
    msys_address1floor: WebAttribute<Account_Select, { msys_address1floor: string | null }, {  }>;
    msys_address1houseletter: WebAttribute<Account_Select, { msys_address1houseletter: string | null }, {  }>;
    msys_address1housenumber: WebAttribute<Account_Select, { msys_address1housenumber: string | null }, {  }>;
    msys_address1locationonfloor: WebAttribute<Account_Select, { msys_address1locationonfloor: string | null }, {  }>;
    msys_address1municipality_guid: WebAttribute<Account_Select, { msys_address1municipality_guid: string | null }, { msys_address1municipality_formatted?: string }>;
    msys_address1postalcode_guid: WebAttribute<Account_Select, { msys_address1postalcode_guid: string | null }, { msys_address1postalcode_formatted?: string }>;
    msys_address1streetname: WebAttribute<Account_Select, { msys_address1streetname: string | null }, {  }>;
    msys_arrearscase_guid: WebAttribute<Account_Select, { msys_arrearscase_guid: string | null }, { msys_arrearscase_formatted?: string }>;
    msys_associationcommitteemembership_guid: WebAttribute<Account_Select, { msys_associationcommitteemembership_guid: string | null }, { msys_associationcommitteemembership_formatted?: string }>;
    msys_combinedaddress: WebAttribute<Account_Select, { msys_combinedaddress: string | null }, {  }>;
    msys_constitutiondayisdayoff: WebAttribute<Account_Select, { msys_constitutiondayisdayoff: boolean | null }, {  }>;
    msys_cvrnum: WebAttribute<Account_Select, { msys_cvrnum: string | null }, {  }>;
    msys_debtor: WebAttribute<Account_Select, { msys_debtor: boolean | null }, {  }>;
    msys_emailtemplateeventcancellationreceipt_guid: WebAttribute<Account_Select, { msys_emailtemplateeventcancellationreceipt_guid: string | null }, { msys_emailtemplateeventcancellationreceipt_formatted?: string }>;
    msys_emailtemplateeventsignupreceipt_guid: WebAttribute<Account_Select, { msys_emailtemplateeventsignupreceipt_guid: string | null }, { msys_emailtemplateeventsignupreceipt_formatted?: string }>;
    msys_emailtemplateeventsignupreceiptphysical_guid: WebAttribute<Account_Select, { msys_emailtemplateeventsignupreceiptphysical_guid: string | null }, { msys_emailtemplateeventsignupreceiptphysical_formatted?: string }>;
    msys_emailtemplateeventsignupreceiptvirtual_guid: WebAttribute<Account_Select, { msys_emailtemplateeventsignupreceiptvirtual_guid: string | null }, { msys_emailtemplateeventsignupreceiptvirtual_formatted?: string }>;
    msys_emailtemplateeventsignupwaitlist_guid: WebAttribute<Account_Select, { msys_emailtemplateeventsignupwaitlist_guid: string | null }, { msys_emailtemplateeventsignupwaitlist_formatted?: string }>;
    msys_emailtemplateeventwaitinglistoffer_guid: WebAttribute<Account_Select, { msys_emailtemplateeventwaitinglistoffer_guid: string | null }, { msys_emailtemplateeventwaitinglistoffer_formatted?: string }>;
    msys_emailtemplateeventwaitinglistpromotion_guid: WebAttribute<Account_Select, { msys_emailtemplateeventwaitinglistpromotion_guid: string | null }, { msys_emailtemplateeventwaitinglistpromotion_formatted?: string }>;
    msys_emailtemplatewaitlistpromotionphysical_guid: WebAttribute<Account_Select, { msys_emailtemplatewaitlistpromotionphysical_guid: string | null }, { msys_emailtemplatewaitlistpromotionphysical_formatted?: string }>;
    msys_emailtemplatewaitlistpromotionvirtual_guid: WebAttribute<Account_Select, { msys_emailtemplatewaitlistpromotionvirtual_guid: string | null }, { msys_emailtemplatewaitlistpromotionvirtual_formatted?: string }>;
    msys_erpaccount: WebAttribute<Account_Select, { msys_erpaccount: string | null }, {  }>;
    msys_erpcompanycode: WebAttribute<Account_Select, { msys_erpcompanycode: string | null }, {  }>;
    msys_erpcostlocation: WebAttribute<Account_Select, { msys_erpcostlocation: string | null }, {  }>;
    msys_erptype: WebAttribute<Account_Select, { msys_erptype: string | null }, {  }>;
    msys_eventcancellationreceipt: WebAttribute<Account_Select, { msys_eventcancellationreceipt: string | null }, {  }>;
    msys_eventsignupreceipt: WebAttribute<Account_Select, { msys_eventsignupreceipt: string | null }, {  }>;
    msys_extid: WebAttribute<Account_Select, { msys_extid: string | null }, {  }>;
    msys_hideonselfservice: WebAttribute<Account_Select, { msys_hideonselfservice: boolean | null }, {  }>;
    msys_invoicingblocked: WebAttribute<Account_Select, { msys_invoicingblocked: boolean | null }, {  }>;
    msys_mailboxforsendingemails_guid: WebAttribute<Account_Select, { msys_mailboxforsendingemails_guid: string | null }, { msys_mailboxforsendingemails_formatted?: string }>;
    msys_nocvrnum: WebAttribute<Account_Select, { msys_nocvrnum: boolean | null }, {  }>;
    msys_offerspayrollpayment: WebAttribute<Account_Select, { msys_offerspayrollpayment: boolean | null }, {  }>;
    msys_pictureid: WebAttribute<Account_Select, { msys_pictureid: string | null }, {  }>;
    msys_placeofeducation: WebAttribute<Account_Select, { msys_placeofeducation: boolean | null }, {  }>;
    msys_postalcodemissing: WebAttribute<Account_Select, { msys_postalcodemissing: boolean | null }, {  }>;
    msys_primarypaymentmethod_guid: WebAttribute<Account_Select, { msys_primarypaymentmethod_guid: string | null }, { msys_primarypaymentmethod_formatted?: string }>;
    msys_publicavailable: WebAttribute<Account_Select, { msys_publicavailable: boolean | null }, {  }>;
    msys_shouldcreateexternaleventpostings: WebAttribute<Account_Select, { msys_shouldcreateexternaleventpostings: boolean | null }, {  }>;
    msys_subunion_guid: WebAttribute<Account_Select, { msys_subunion_guid: string | null }, { msys_subunion_formatted?: string }>;
    msys_topmaincompany_guid: WebAttribute<Account_Select, { msys_topmaincompany_guid: string | null }, { msys_topmaincompany_formatted?: string }>;
    msys_uvmnum: WebAttribute<Account_Select, { msys_uvmnum: string | null }, {  }>;
    msys_workplacetype_guid: WebAttribute<Account_Select, { msys_workplacetype_guid: string | null }, { msys_workplacetype_formatted?: string }>;
    name: WebAttribute<Account_Select, { name: string | null }, {  }>;
    numberofemployees: WebAttribute<Account_Select, { numberofemployees: number | null }, {  }>;
    onholdtime: WebAttribute<Account_Select, { onholdtime: number | null }, {  }>;
    overriddencreatedon: WebAttribute<Account_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<Account_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    ownershipcode: WebAttribute<Account_Select, { ownershipcode: account_ownershipcode | null }, { ownershipcode_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<Account_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<Account_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<Account_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    parentaccountid_guid: WebAttribute<Account_Select, { parentaccountid_guid: string | null }, { parentaccountid_formatted?: string }>;
    participatesinworkflow: WebAttribute<Account_Select, { participatesinworkflow: boolean | null }, {  }>;
    paymenttermscode: WebAttribute<Account_Select, { paymenttermscode: account_paymenttermscode | null }, { paymenttermscode_formatted?: string }>;
    preferredappointmentdaycode: WebAttribute<Account_Select, { preferredappointmentdaycode: account_preferredappointmentdaycode | null }, { preferredappointmentdaycode_formatted?: string }>;
    preferredappointmenttimecode: WebAttribute<Account_Select, { preferredappointmenttimecode: account_preferredappointmenttimecode | null }, { preferredappointmenttimecode_formatted?: string }>;
    preferredcontactmethodcode: WebAttribute<Account_Select, { preferredcontactmethodcode: account_preferredcontactmethodcode | null }, { preferredcontactmethodcode_formatted?: string }>;
    preferredsystemuserid_guid: WebAttribute<Account_Select, { preferredsystemuserid_guid: string | null }, { preferredsystemuserid_formatted?: string }>;
    primarycontactid_guid: WebAttribute<Account_Select, { primarycontactid_guid: string | null }, { primarycontactid_formatted?: string }>;
    primarysatoriid: WebAttribute<Account_Select, { primarysatoriid: string | null }, {  }>;
    primarytwitterid: WebAttribute<Account_Select, { primarytwitterid: string | null }, {  }>;
    processid: WebAttribute<Account_Select, { processid: string | null }, {  }>;
    revenue: WebAttribute<Account_Select, { revenue: number | null; transactioncurrencyid_guid: string | null }, { revenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
    revenue_base: WebAttribute<Account_Select, { revenue_base: number | null; transactioncurrencyid_guid: string | null }, { revenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    sharesoutstanding: WebAttribute<Account_Select, { sharesoutstanding: number | null }, {  }>;
    shippingmethodcode: WebAttribute<Account_Select, { shippingmethodcode: account_shippingmethodcode | null }, { shippingmethodcode_formatted?: string }>;
    sic: WebAttribute<Account_Select, { sic: string | null }, {  }>;
    slaid_guid: WebAttribute<Account_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
    slainvokedid_guid: WebAttribute<Account_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
    stageid: WebAttribute<Account_Select, { stageid: string | null }, {  }>;
    statecode: WebAttribute<Account_Select, { statecode: account_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<Account_Select, { statuscode: account_statuscode | null }, { statuscode_formatted?: string }>;
    stockexchange: WebAttribute<Account_Select, { stockexchange: string | null }, {  }>;
    telephone1: WebAttribute<Account_Select, { telephone1: string | null }, {  }>;
    telephone2: WebAttribute<Account_Select, { telephone2: string | null }, {  }>;
    telephone3: WebAttribute<Account_Select, { telephone3: string | null }, {  }>;
    territorycode: WebAttribute<Account_Select, { territorycode: account_territorycode | null }, { territorycode_formatted?: string }>;
    tickersymbol: WebAttribute<Account_Select, { tickersymbol: string | null }, {  }>;
    timespentbymeonemailandmeetings: WebAttribute<Account_Select, { timespentbymeonemailandmeetings: string | null }, {  }>;
    timezoneruleversionnumber: WebAttribute<Account_Select, { timezoneruleversionnumber: number | null }, {  }>;
    transactioncurrencyid_guid: WebAttribute<Account_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
    traversedpath: WebAttribute<Account_Select, { traversedpath: string | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<Account_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<Account_Select, { versionnumber: number | null }, {  }>;
    websiteurl: WebAttribute<Account_Select, { websiteurl: string | null }, {  }>;
  }
  interface Account_Filter {
    accountcategorycode: account_accountcategorycode;
    accountclassificationcode: account_accountclassificationcode;
    accountid: XQW.Guid;
    accountnumber: string;
    accountratingcode: account_accountratingcode;
    address1_addressid: XQW.Guid;
    address1_addresstypecode: account_address1_addresstypecode;
    address1_city: string;
    address1_composite: string;
    address1_country: string;
    address1_county: string;
    address1_fax: string;
    address1_freighttermscode: account_address1_freighttermscode;
    address1_latitude: number;
    address1_line1: string;
    address1_line2: string;
    address1_line3: string;
    address1_longitude: number;
    address1_name: string;
    address1_postalcode: string;
    address1_postofficebox: string;
    address1_primarycontactname: string;
    address1_shippingmethodcode: account_address1_shippingmethodcode;
    address1_stateorprovince: string;
    address1_telephone1: string;
    address1_telephone2: string;
    address1_telephone3: string;
    address1_upszone: string;
    address1_utcoffset: number;
    address2_addressid: XQW.Guid;
    address2_addresstypecode: account_address2_addresstypecode;
    address2_city: string;
    address2_composite: string;
    address2_country: string;
    address2_county: string;
    address2_fax: string;
    address2_freighttermscode: account_address2_freighttermscode;
    address2_latitude: number;
    address2_line1: string;
    address2_line2: string;
    address2_line3: string;
    address2_longitude: number;
    address2_name: string;
    address2_postalcode: string;
    address2_postofficebox: string;
    address2_primarycontactname: string;
    address2_shippingmethodcode: account_address2_shippingmethodcode;
    address2_stateorprovince: string;
    address2_telephone1: string;
    address2_telephone2: string;
    address2_telephone3: string;
    address2_upszone: string;
    address2_utcoffset: number;
    adx_createdbyipaddress: string;
    adx_createdbyusername: string;
    adx_modifiedbyipaddress: string;
    adx_modifiedbyusername: string;
    aging30: number;
    aging30_base: number;
    aging60: number;
    aging60_base: number;
    aging90: number;
    aging90_base: number;
    businesstypecode: account_businesstypecode;
    createdby_guid: XQW.Guid;
    createdbyexternalparty_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    creditlimit: number;
    creditlimit_base: number;
    creditonhold: boolean;
    customersizecode: account_customersizecode;
    customertypecode: account_customertypecode;
    description: string;
    donotbulkemail: boolean;
    donotbulkpostalmail: boolean;
    donotemail: boolean;
    donotfax: boolean;
    donotphone: boolean;
    donotpostalmail: boolean;
    donotsendmm: boolean;
    emailaddress1: string;
    emailaddress2: string;
    emailaddress3: string;
    entityimageid: XQW.Guid;
    exchangerate: any;
    fax: string;
    followemail: boolean;
    ftpsiteurl: string;
    importsequencenumber: number;
    industrycode: account_industrycode;
    isprivate: boolean;
    lastonholdtime: Date;
    lastusedincampaign: Date;
    marketcap: number;
    marketcap_base: number;
    marketingonly: boolean;
    masterid_guid: XQW.Guid;
    merged: boolean;
    modifiedby_guid: XQW.Guid;
    modifiedbyexternalparty_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    msa_managingpartnerid_guid: XQW.Guid;
    msys_accountnumber: string;
    msys_accounttype: msys_accounttype;
    msys_accountvalidated: boolean;
    msys_address1_region_guid: XQW.Guid;
    msys_address1city_guid: XQW.Guid;
    msys_address1country_guid: XQW.Guid;
    msys_address1floor: string;
    msys_address1houseletter: string;
    msys_address1housenumber: string;
    msys_address1locationonfloor: string;
    msys_address1municipality_guid: XQW.Guid;
    msys_address1postalcode_guid: XQW.Guid;
    msys_address1streetname: string;
    msys_arrearscase_guid: XQW.Guid;
    msys_associationcommitteemembership_guid: XQW.Guid;
    msys_combinedaddress: string;
    msys_constitutiondayisdayoff: boolean;
    msys_cvrnum: string;
    msys_debtor: boolean;
    msys_emailtemplateeventcancellationreceipt_guid: XQW.Guid;
    msys_emailtemplateeventsignupreceipt_guid: XQW.Guid;
    msys_emailtemplateeventsignupreceiptphysical_guid: XQW.Guid;
    msys_emailtemplateeventsignupreceiptvirtual_guid: XQW.Guid;
    msys_emailtemplateeventsignupwaitlist_guid: XQW.Guid;
    msys_emailtemplateeventwaitinglistoffer_guid: XQW.Guid;
    msys_emailtemplateeventwaitinglistpromotion_guid: XQW.Guid;
    msys_emailtemplatewaitlistpromotionphysical_guid: XQW.Guid;
    msys_emailtemplatewaitlistpromotionvirtual_guid: XQW.Guid;
    msys_erpaccount: string;
    msys_erpcompanycode: string;
    msys_erpcostlocation: string;
    msys_erptype: string;
    msys_eventcancellationreceipt: string;
    msys_eventsignupreceipt: string;
    msys_extid: string;
    msys_hideonselfservice: boolean;
    msys_invoicingblocked: boolean;
    msys_mailboxforsendingemails_guid: XQW.Guid;
    msys_nocvrnum: boolean;
    msys_offerspayrollpayment: boolean;
    msys_pictureid: XQW.Guid;
    msys_placeofeducation: boolean;
    msys_postalcodemissing: boolean;
    msys_primarypaymentmethod_guid: XQW.Guid;
    msys_publicavailable: boolean;
    msys_shouldcreateexternaleventpostings: boolean;
    msys_subunion_guid: XQW.Guid;
    msys_topmaincompany_guid: XQW.Guid;
    msys_uvmnum: string;
    msys_workplacetype_guid: XQW.Guid;
    name: string;
    numberofemployees: number;
    onholdtime: number;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    ownershipcode: account_ownershipcode;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    parentaccountid_guid: XQW.Guid;
    participatesinworkflow: boolean;
    paymenttermscode: account_paymenttermscode;
    preferredappointmentdaycode: account_preferredappointmentdaycode;
    preferredappointmenttimecode: account_preferredappointmenttimecode;
    preferredcontactmethodcode: account_preferredcontactmethodcode;
    preferredsystemuserid_guid: XQW.Guid;
    primarycontactid_guid: XQW.Guid;
    primarysatoriid: string;
    primarytwitterid: string;
    processid: XQW.Guid;
    revenue: number;
    revenue_base: number;
    sharesoutstanding: number;
    shippingmethodcode: account_shippingmethodcode;
    sic: string;
    slaid_guid: XQW.Guid;
    slainvokedid_guid: XQW.Guid;
    stageid: XQW.Guid;
    statecode: account_statecode;
    statuscode: account_statuscode;
    stockexchange: string;
    telephone1: string;
    telephone2: string;
    telephone3: string;
    territorycode: account_territorycode;
    tickersymbol: string;
    timespentbymeonemailandmeetings: string;
    timezoneruleversionnumber: number;
    transactioncurrencyid_guid: XQW.Guid;
    traversedpath: string;
    utcconversiontimezonecode: number;
    versionnumber: number;
    websiteurl: string;
  }
  interface Account_Expand {
    Account_ActivityPointers: WebExpand<Account_Expand, ActivityPointer_Select, ActivityPointer_Filter, { Account_ActivityPointers: ActivityPointer_Result[] }>;
    Account_Annotation: WebExpand<Account_Expand, Annotation_Select, Annotation_Filter, { Account_Annotation: Annotation_Result[] }>;
    Account_Appointments: WebExpand<Account_Expand, Appointment_Select, Appointment_Filter, { Account_Appointments: Appointment_Result[] }>;
    Account_Email_EmailSender: WebExpand<Account_Expand, Email_Select, Email_Filter, { Account_Email_EmailSender: Email_Result[] }>;
    Account_Email_SendersAccount: WebExpand<Account_Expand, Email_Select, Email_Filter, { Account_Email_SendersAccount: Email_Result[] }>;
    Account_Emails: WebExpand<Account_Expand, Email_Select, Email_Filter, { Account_Emails: Email_Result[] }>;
    Account_Phonecalls: WebExpand<Account_Expand, PhoneCall_Select, PhoneCall_Filter, { Account_Phonecalls: PhoneCall_Result[] }>;
    Account_Tasks: WebExpand<Account_Expand, Task_Select, Task_Filter, { Account_Tasks: Task_Result[] }>;
    account_activity_parties: WebExpand<Account_Expand, ActivityParty_Select, ActivityParty_Filter, { account_activity_parties: ActivityParty_Result[] }>;
    account_connections1: WebExpand<Account_Expand, Connection_Select, Connection_Filter, { account_connections1: Connection_Result[] }>;
    account_connections2: WebExpand<Account_Expand, Connection_Select, Connection_Filter, { account_connections2: Connection_Result[] }>;
    account_master_account: WebExpand<Account_Expand, Account_Select, Account_Filter, { account_master_account: Account_Result[] }>;
    account_msys_InternalNotes: WebExpand<Account_Expand, msys_InternalNote_Select, msys_InternalNote_Filter, { account_msys_InternalNotes: msys_InternalNote_Result[] }>;
    account_parent_account: WebExpand<Account_Expand, Account_Select, Account_Filter, { account_parent_account: Account_Result[] }>;
    contact_customer_accounts: WebExpand<Account_Expand, Contact_Select, Contact_Filter, { contact_customer_accounts: Contact_Result[] }>;
    createdby: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
    createdonbehalfby: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
    masterid: WebExpand<Account_Expand, Account_Select, Account_Filter, { masterid: Account_Result }>;
    modifiedby: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
    modifiedonbehalfby: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
    msa_account_managingpartner: WebExpand<Account_Expand, Account_Select, Account_Filter, { msa_account_managingpartner: Account_Result[] }>;
    msa_contact_managingpartner: WebExpand<Account_Expand, Contact_Select, Contact_Filter, { msa_contact_managingpartner: Contact_Result[] }>;
    msa_managingpartnerid: WebExpand<Account_Expand, Account_Select, Account_Filter, { msa_managingpartnerid: Account_Result }>;
    msys_Account_msys_CommitteeMember_msys_CommitteeMember: WebExpand<Account_Expand, msys_CommitteeMember_Select, msys_CommitteeMember_Filter, { msys_Account_msys_CommitteeMember_msys_CommitteeMember: msys_CommitteeMember_Result[] }>;
    msys_Address1City: WebExpand<Account_Expand, msys_City_Select, msys_City_Filter, { msys_Address1City: msys_City_Result }>;
    msys_Address1Country: WebExpand<Account_Expand, msys_Country_Select, msys_Country_Filter, { msys_Address1Country: msys_Country_Result }>;
    msys_Address1Municipality: WebExpand<Account_Expand, msys_Municipality_Select, msys_Municipality_Filter, { msys_Address1Municipality: msys_Municipality_Result }>;
    msys_Address1PostalCode: WebExpand<Account_Expand, msys_PostalCode_Select, msys_PostalCode_Filter, { msys_Address1PostalCode: msys_PostalCode_Result }>;
    msys_Address1_Region: WebExpand<Account_Expand, msys_Region_Select, msys_Region_Filter, { msys_Address1_Region: msys_Region_Result }>;
    msys_ArrearsCase: WebExpand<Account_Expand, msys_ArrearsCase_Select, msys_ArrearsCase_Filter, { msys_ArrearsCase: msys_ArrearsCase_Result }>;
    msys_AssociationCommitteemembership: WebExpand<Account_Expand, Account_Select, Account_Filter, { msys_AssociationCommitteemembership: Account_Result }>;
    msys_Case_Account_AdditionalParties: WebExpand<Account_Expand, msys_Case_Select, msys_Case_Filter, { msys_Case_Account_AdditionalParties: msys_Case_Result[] }>;
    msys_EmailTemplateEventCancellationReceipt: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateEventCancellationReceipt: msys_EmailTemplate_Result }>;
    msys_EmailTemplateEventSignupReceipt: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateEventSignupReceipt: msys_EmailTemplate_Result }>;
    msys_EmailTemplateEventSignupReceiptPhysical: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateEventSignupReceiptPhysical: msys_EmailTemplate_Result }>;
    msys_EmailTemplateEventSignupReceiptVirtual: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateEventSignupReceiptVirtual: msys_EmailTemplate_Result }>;
    msys_EmailTemplateEventSignupWaitlist: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateEventSignupWaitlist: msys_EmailTemplate_Result }>;
    msys_EmailTemplateEventWaitingListOffer: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateEventWaitingListOffer: msys_EmailTemplate_Result }>;
    msys_EmailTemplateEventWaitingListPromotion: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateEventWaitingListPromotion: msys_EmailTemplate_Result }>;
    msys_EmailTemplateWaitListPromotionPhysical: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateWaitListPromotionPhysical: msys_EmailTemplate_Result }>;
    msys_EmailTemplateWaitListPromotionVirtual: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_EmailTemplateWaitListPromotionVirtual: msys_EmailTemplate_Result }>;
    msys_MailboxForSendingEmails: WebExpand<Account_Expand, Mailbox_Select, Mailbox_Filter, { msys_MailboxForSendingEmails: Mailbox_Result }>;
    msys_PrimaryPaymentMethod: WebExpand<Account_Expand, msys_PaymentMethod_Select, msys_PaymentMethod_Filter, { msys_PrimaryPaymentMethod: msys_PaymentMethod_Result }>;
    msys_SubUnion: WebExpand<Account_Expand, Team_Select, Team_Filter, { msys_SubUnion: Team_Result }>;
    msys_TopMainCompany: WebExpand<Account_Expand, Account_Select, Account_Filter, { msys_TopMainCompany: Account_Result }>;
    msys_WorkplaceType: WebExpand<Account_Expand, msys_WorkplaceType_Select, msys_WorkplaceType_Filter, { msys_WorkplaceType: msys_WorkplaceType_Result }>;
    msys_account_AssociationCommitteemembership_account: WebExpand<Account_Expand, Account_Select, Account_Filter, { msys_account_AssociationCommitteemembership_account: Account_Result[] }>;
    msys_account_TopMainCompany_account: WebExpand<Account_Expand, Account_Select, Account_Filter, { msys_account_TopMainCompany_account: Account_Result[] }>;
    msys_account_msys_arrearscase_656: WebExpand<Account_Expand, msys_ArrearsCase_Select, msys_ArrearsCase_Filter, { msys_account_msys_arrearscase_656: msys_ArrearsCase_Result[] }>;
    msys_account_msys_case: WebExpand<Account_Expand, msys_Case_Select, msys_Case_Filter, { msys_account_msys_case: msys_Case_Result[] }>;
    msys_account_msys_case_primary_party: WebExpand<Account_Expand, msys_Case_Select, msys_Case_Filter, { msys_account_msys_case_primary_party: msys_Case_Result[] }>;
    msys_account_msys_customerdiscount_51: WebExpand<Account_Expand, msys_CustomerDiscount_Select, msys_CustomerDiscount_Filter, { msys_account_msys_customerdiscount_51: msys_CustomerDiscount_Result[] }>;
    msys_account_msys_invoice_928: WebExpand<Account_Expand, msys_Invoice_Select, msys_Invoice_Filter, { msys_account_msys_invoice_928: msys_Invoice_Result[] }>;
    msys_account_msys_invoicedivision_313: WebExpand<Account_Expand, msys_InvoiceDivision_Select, msys_InvoiceDivision_Filter, { msys_account_msys_invoicedivision_313: msys_InvoiceDivision_Result[] }>;
    msys_account_msys_membership_549: WebExpand<Account_Expand, msys_Membership_Select, msys_Membership_Filter, { msys_account_msys_membership_549: msys_Membership_Result[] }>;
    msys_account_msys_payment_960: WebExpand<Account_Expand, msys_Payment_Select, msys_Payment_Filter, { msys_account_msys_payment_960: msys_Payment_Result[] }>;
    msys_account_msys_paymentmethod_452: WebExpand<Account_Expand, msys_PaymentMethod_Select, msys_PaymentMethod_Filter, { msys_account_msys_paymentmethod_452: msys_PaymentMethod_Result[] }>;
    msys_account_msys_selfservicerights_48: WebExpand<Account_Expand, msys_SelfServiceRights_Select, msys_SelfServiceRights_Filter, { msys_account_msys_selfservicerights_48: msys_SelfServiceRights_Result[] }>;
    msys_account_msys_taxreport_639: WebExpand<Account_Expand, msys_TaxReport_Select, msys_TaxReport_Filter, { msys_account_msys_taxreport_639: msys_TaxReport_Result[] }>;
    msys_account_msys_transaction_933: WebExpand<Account_Expand, msys_Transaction_Select, msys_Transaction_Filter, { msys_account_msys_transaction_933: msys_Transaction_Result[] }>;
    msys_agreement_Account_account: WebExpand<Account_Expand, msys_Agreement_Select, msys_Agreement_Filter, { msys_agreement_Account_account: msys_Agreement_Result[] }>;
    msys_agreementconnection_Account_account: WebExpand<Account_Expand, msys_AgreementConnection_Select, msys_AgreementConnection_Filter, { msys_agreementconnection_Account_account: msys_AgreementConnection_Result[] }>;
    msys_committee_AccountUnion_account: WebExpand<Account_Expand, msys_Committee_Select, msys_Committee_Filter, { msys_committee_AccountUnion_account: msys_Committee_Result[] }>;
    msys_committeemember_AccountAppointedBy_account: WebExpand<Account_Expand, msys_CommitteeMember_Select, msys_CommitteeMember_Filter, { msys_committeemember_AccountAppointedBy_account: msys_CommitteeMember_Result[] }>;
    msys_configuration_MainUnion_account: WebExpand<Account_Expand, msys_Configuration_Select, msys_Configuration_Filter, { msys_configuration_MainUnion_account: msys_Configuration_Result[] }>;
    msys_contact_PrimaryWorkplace_account: WebExpand<Account_Expand, Contact_Select, Contact_Filter, { msys_contact_PrimaryWorkplace_account: Contact_Result[] }>;
    msys_contact_SecondaryUnion_account: WebExpand<Account_Expand, Contact_Select, Contact_Filter, { msys_contact_SecondaryUnion_account: Contact_Result[] }>;
    msys_debitorsettlement_Account_account: WebExpand<Account_Expand, msys_DebitorSettlement_Select, msys_DebitorSettlement_Filter, { msys_debitorsettlement_Account_account: msys_DebitorSettlement_Result[] }>;
    msys_education_PlaceOfEducation_account: WebExpand<Account_Expand, msys_Education_Select, msys_Education_Filter, { msys_education_PlaceOfEducation_account: msys_Education_Result[] }>;
    msys_educationtype_PlaceOfStudy_account: WebExpand<Account_Expand, msys_EducationType_Select, msys_EducationType_Filter, { msys_educationtype_PlaceOfStudy_account: msys_EducationType_Result[] }>;
    msys_employment_Workplace_account: WebExpand<Account_Expand, msys_Employment_Select, msys_Employment_Filter, { msys_employment_Workplace_account: msys_Employment_Result[] }>;
    msys_event_Organizer_account: WebExpand<Account_Expand, msys_Event_Select, msys_Event_Filter, { msys_event_Organizer_account: msys_Event_Result[] }>;
    msys_event_Venue_account: WebExpand<Account_Expand, msys_Event_Select, msys_Event_Filter, { msys_event_Venue_account: msys_Event_Result[] }>;
    msys_financetype_Account_account: WebExpand<Account_Expand, msys_Financetype_Select, msys_Financetype_Filter, { msys_financetype_Account_account: msys_Financetype_Result[] }>;
    msys_msys_answer_account_msys_DynamicListAnswer: WebExpand<Account_Expand, msys_Answer_Select, msys_Answer_Filter, { msys_msys_answer_account_msys_DynamicListAnswer: msys_Answer_Result[] }>;
    msys_msys_emailtemplate_account_msys_ValidationEntity: WebExpand<Account_Expand, msys_EmailTemplate_Select, msys_EmailTemplate_Filter, { msys_msys_emailtemplate_account_msys_ValidationEntity: msys_EmailTemplate_Result[] }>;
    msys_paymentmethod_PayrollAt_account: WebExpand<Account_Expand, msys_PaymentMethod_Select, msys_PaymentMethod_Filter, { msys_paymentmethod_PayrollAt_account: msys_PaymentMethod_Result[] }>;
    msys_payrollrun_Account_account: WebExpand<Account_Expand, msys_PayrollRun_Select, msys_PayrollRun_Filter, { msys_payrollrun_Account_account: msys_PayrollRun_Result[] }>;
    msys_placementrule_Account_account: WebExpand<Account_Expand, msys_PlacementRule_Select, msys_PlacementRule_Filter, { msys_placementrule_Account_account: msys_PlacementRule_Result[] }>;
    msys_product_Related_Account_account: WebExpand<Account_Expand, msys_Product_Select, msys_Product_Filter, { msys_product_Related_Account_account: msys_Product_Result[] }>;
    msys_registration_CompanyPayer_account: WebExpand<Account_Expand, msys_Registration_Select, msys_Registration_Filter, { msys_registration_CompanyPayer_account: msys_Registration_Result[] }>;
    msys_team_SubUnion_account: WebExpand<Account_Expand, Team_Select, Team_Filter, { msys_team_SubUnion_account: Team_Result[] }>;
    msys_team_TopLevelWorkplace_account: WebExpand<Account_Expand, Team_Select, Team_Filter, { msys_team_TopLevelWorkplace_account: Team_Result[] }>;
    ownerid: WebExpand<Account_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
    owningteam: WebExpand<Account_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
    owninguser: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
    parentaccountid: WebExpand<Account_Expand, Account_Select, Account_Filter, { parentaccountid: Account_Result }>;
    preferredsystemuserid: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { preferredsystemuserid: SystemUser_Result }>;
    primarycontactid: WebExpand<Account_Expand, Contact_Select, Contact_Filter, { primarycontactid: Contact_Result }>;
  }
  interface Account_FormattedResult {
    accountcategorycode_formatted?: string;
    accountclassificationcode_formatted?: string;
    accountratingcode_formatted?: string;
    address1_addresstypecode_formatted?: string;
    address1_freighttermscode_formatted?: string;
    address1_shippingmethodcode_formatted?: string;
    address2_addresstypecode_formatted?: string;
    address2_freighttermscode_formatted?: string;
    address2_shippingmethodcode_formatted?: string;
    aging30_base_formatted?: string;
    aging30_formatted?: string;
    aging60_base_formatted?: string;
    aging60_formatted?: string;
    aging90_base_formatted?: string;
    aging90_formatted?: string;
    businesstypecode_formatted?: string;
    createdby_formatted?: string;
    createdbyexternalparty_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    creditlimit_base_formatted?: string;
    creditlimit_formatted?: string;
    customersizecode_formatted?: string;
    customertypecode_formatted?: string;
    industrycode_formatted?: string;
    lastonholdtime_formatted?: string;
    lastusedincampaign_formatted?: string;
    marketcap_base_formatted?: string;
    marketcap_formatted?: string;
    masterid_formatted?: string;
    modifiedby_formatted?: string;
    modifiedbyexternalparty_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    msa_managingpartnerid_formatted?: string;
    msys_accounttype_formatted?: string;
    msys_address1_region_formatted?: string;
    msys_address1city_formatted?: string;
    msys_address1country_formatted?: string;
    msys_address1municipality_formatted?: string;
    msys_address1postalcode_formatted?: string;
    msys_arrearscase_formatted?: string;
    msys_associationcommitteemembership_formatted?: string;
    msys_emailtemplateeventcancellationreceipt_formatted?: string;
    msys_emailtemplateeventsignupreceipt_formatted?: string;
    msys_emailtemplateeventsignupreceiptphysical_formatted?: string;
    msys_emailtemplateeventsignupreceiptvirtual_formatted?: string;
    msys_emailtemplateeventsignupwaitlist_formatted?: string;
    msys_emailtemplateeventwaitinglistoffer_formatted?: string;
    msys_emailtemplateeventwaitinglistpromotion_formatted?: string;
    msys_emailtemplatewaitlistpromotionphysical_formatted?: string;
    msys_emailtemplatewaitlistpromotionvirtual_formatted?: string;
    msys_mailboxforsendingemails_formatted?: string;
    msys_primarypaymentmethod_formatted?: string;
    msys_subunion_formatted?: string;
    msys_topmaincompany_formatted?: string;
    msys_workplacetype_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    ownershipcode_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    parentaccountid_formatted?: string;
    paymenttermscode_formatted?: string;
    preferredappointmentdaycode_formatted?: string;
    preferredappointmenttimecode_formatted?: string;
    preferredcontactmethodcode_formatted?: string;
    preferredsystemuserid_formatted?: string;
    primarycontactid_formatted?: string;
    revenue_base_formatted?: string;
    revenue_formatted?: string;
    shippingmethodcode_formatted?: string;
    slaid_formatted?: string;
    slainvokedid_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
    territorycode_formatted?: string;
    transactioncurrencyid_formatted?: string;
  }
  interface Account_Result extends Account_Base, Account_Relationships {
    "@odata.etag": string;
    createdby_guid: string | null;
    createdbyexternalparty_guid: string | null;
    createdonbehalfby_guid: string | null;
    masterid_guid: string | null;
    modifiedby_guid: string | null;
    modifiedbyexternalparty_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    msa_managingpartnerid_guid: string | null;
    msys_address1_region_guid: string | null;
    msys_address1city_guid: string | null;
    msys_address1country_guid: string | null;
    msys_address1municipality_guid: string | null;
    msys_address1postalcode_guid: string | null;
    msys_arrearscase_guid: string | null;
    msys_associationcommitteemembership_guid: string | null;
    msys_emailtemplateeventcancellationreceipt_guid: string | null;
    msys_emailtemplateeventsignupreceipt_guid: string | null;
    msys_emailtemplateeventsignupreceiptphysical_guid: string | null;
    msys_emailtemplateeventsignupreceiptvirtual_guid: string | null;
    msys_emailtemplateeventsignupwaitlist_guid: string | null;
    msys_emailtemplateeventwaitinglistoffer_guid: string | null;
    msys_emailtemplateeventwaitinglistpromotion_guid: string | null;
    msys_emailtemplatewaitlistpromotionphysical_guid: string | null;
    msys_emailtemplatewaitlistpromotionvirtual_guid: string | null;
    msys_mailboxforsendingemails_guid: string | null;
    msys_primarypaymentmethod_guid: string | null;
    msys_subunion_guid: string | null;
    msys_topmaincompany_guid: string | null;
    msys_workplacetype_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
    parentaccountid_guid: string | null;
    preferredsystemuserid_guid: string | null;
    primarycontactid_guid: string | null;
    slaid_guid: string | null;
    slainvokedid_guid: string | null;
    transactioncurrencyid_guid: string | null;
  }
  interface Account_RelatedOne {
    createdby: WebMappingRetrieve<XDT.SystemUser_Select,XDT.SystemUser_Expand,XDT.SystemUser_Filter,XDT.SystemUser_Fixed,XDT.SystemUser_Result,XDT.SystemUser_FormattedResult>;
    createdonbehalfby: WebMappingRetrieve<XDT.SystemUser_Select,XDT.SystemUser_Expand,XDT.SystemUser_Filter,XDT.SystemUser_Fixed,XDT.SystemUser_Result,XDT.SystemUser_FormattedResult>;
    masterid: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    modifiedby: WebMappingRetrieve<XDT.SystemUser_Select,XDT.SystemUser_Expand,XDT.SystemUser_Filter,XDT.SystemUser_Fixed,XDT.SystemUser_Result,XDT.SystemUser_FormattedResult>;
    modifiedonbehalfby: WebMappingRetrieve<XDT.SystemUser_Select,XDT.SystemUser_Expand,XDT.SystemUser_Filter,XDT.SystemUser_Fixed,XDT.SystemUser_Result,XDT.SystemUser_FormattedResult>;
    msa_managingpartnerid: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    msys_Address1City: WebMappingRetrieve<XDT.msys_City_Select,XDT.msys_City_Expand,XDT.msys_City_Filter,XDT.msys_City_Fixed,XDT.msys_City_Result,XDT.msys_City_FormattedResult>;
    msys_Address1Country: WebMappingRetrieve<XDT.msys_Country_Select,XDT.msys_Country_Expand,XDT.msys_Country_Filter,XDT.msys_Country_Fixed,XDT.msys_Country_Result,XDT.msys_Country_FormattedResult>;
    msys_Address1Municipality: WebMappingRetrieve<XDT.msys_Municipality_Select,XDT.msys_Municipality_Expand,XDT.msys_Municipality_Filter,XDT.msys_Municipality_Fixed,XDT.msys_Municipality_Result,XDT.msys_Municipality_FormattedResult>;
    msys_Address1PostalCode: WebMappingRetrieve<XDT.msys_PostalCode_Select,XDT.msys_PostalCode_Expand,XDT.msys_PostalCode_Filter,XDT.msys_PostalCode_Fixed,XDT.msys_PostalCode_Result,XDT.msys_PostalCode_FormattedResult>;
    msys_Address1_Region: WebMappingRetrieve<XDT.msys_Region_Select,XDT.msys_Region_Expand,XDT.msys_Region_Filter,XDT.msys_Region_Fixed,XDT.msys_Region_Result,XDT.msys_Region_FormattedResult>;
    msys_ArrearsCase: WebMappingRetrieve<XDT.msys_ArrearsCase_Select,XDT.msys_ArrearsCase_Expand,XDT.msys_ArrearsCase_Filter,XDT.msys_ArrearsCase_Fixed,XDT.msys_ArrearsCase_Result,XDT.msys_ArrearsCase_FormattedResult>;
    msys_AssociationCommitteemembership: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    msys_EmailTemplateEventCancellationReceipt: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_EmailTemplateEventSignupReceipt: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_EmailTemplateEventSignupReceiptPhysical: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_EmailTemplateEventSignupReceiptVirtual: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_EmailTemplateEventSignupWaitlist: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_EmailTemplateEventWaitingListOffer: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_EmailTemplateEventWaitingListPromotion: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_EmailTemplateWaitListPromotionPhysical: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_EmailTemplateWaitListPromotionVirtual: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_MailboxForSendingEmails: WebMappingRetrieve<XDT.Mailbox_Select,XDT.Mailbox_Expand,XDT.Mailbox_Filter,XDT.Mailbox_Fixed,XDT.Mailbox_Result,XDT.Mailbox_FormattedResult>;
    msys_PrimaryPaymentMethod: WebMappingRetrieve<XDT.msys_PaymentMethod_Select,XDT.msys_PaymentMethod_Expand,XDT.msys_PaymentMethod_Filter,XDT.msys_PaymentMethod_Fixed,XDT.msys_PaymentMethod_Result,XDT.msys_PaymentMethod_FormattedResult>;
    msys_SubUnion: WebMappingRetrieve<XDT.Team_Select,XDT.Team_Expand,XDT.Team_Filter,XDT.Team_Fixed,XDT.Team_Result,XDT.Team_FormattedResult>;
    msys_TopMainCompany: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    msys_WorkplaceType: WebMappingRetrieve<XDT.msys_WorkplaceType_Select,XDT.msys_WorkplaceType_Expand,XDT.msys_WorkplaceType_Filter,XDT.msys_WorkplaceType_Fixed,XDT.msys_WorkplaceType_Result,XDT.msys_WorkplaceType_FormattedResult>;
    ownerid: WebMappingRetrieve<XDT.SystemUser_Select,XDT.SystemUser_Expand,XDT.SystemUser_Filter,XDT.SystemUser_Fixed,XDT.SystemUser_Result,XDT.SystemUser_FormattedResult> & WebMappingRetrieve<XDT.Team_Select,XDT.Team_Expand,XDT.Team_Filter,XDT.Team_Fixed,XDT.Team_Result,XDT.Team_FormattedResult>;
    owningteam: WebMappingRetrieve<XDT.Team_Select,XDT.Team_Expand,XDT.Team_Filter,XDT.Team_Fixed,XDT.Team_Result,XDT.Team_FormattedResult>;
    owninguser: WebMappingRetrieve<XDT.SystemUser_Select,XDT.SystemUser_Expand,XDT.SystemUser_Filter,XDT.SystemUser_Fixed,XDT.SystemUser_Result,XDT.SystemUser_FormattedResult>;
    parentaccountid: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    preferredsystemuserid: WebMappingRetrieve<XDT.SystemUser_Select,XDT.SystemUser_Expand,XDT.SystemUser_Filter,XDT.SystemUser_Fixed,XDT.SystemUser_Result,XDT.SystemUser_FormattedResult>;
    primarycontactid: WebMappingRetrieve<XDT.Contact_Select,XDT.Contact_Expand,XDT.Contact_Filter,XDT.Contact_Fixed,XDT.Contact_Result,XDT.Contact_FormattedResult>;
  }
  interface Account_RelatedMany {
    Account_ActivityPointers: WebMappingRetrieve<XDT.ActivityPointer_Select,XDT.ActivityPointer_Expand,XDT.ActivityPointer_Filter,XDT.ActivityPointer_Fixed,XDT.ActivityPointer_Result,XDT.ActivityPointer_FormattedResult>;
    Account_Annotation: WebMappingRetrieve<XDT.Annotation_Select,XDT.Annotation_Expand,XDT.Annotation_Filter,XDT.Annotation_Fixed,XDT.Annotation_Result,XDT.Annotation_FormattedResult>;
    Account_Appointments: WebMappingRetrieve<XDT.Appointment_Select,XDT.Appointment_Expand,XDT.Appointment_Filter,XDT.Appointment_Fixed,XDT.Appointment_Result,XDT.Appointment_FormattedResult>;
    Account_Email_EmailSender: WebMappingRetrieve<XDT.Email_Select,XDT.Email_Expand,XDT.Email_Filter,XDT.Email_Fixed,XDT.Email_Result,XDT.Email_FormattedResult>;
    Account_Email_SendersAccount: WebMappingRetrieve<XDT.Email_Select,XDT.Email_Expand,XDT.Email_Filter,XDT.Email_Fixed,XDT.Email_Result,XDT.Email_FormattedResult>;
    Account_Emails: WebMappingRetrieve<XDT.Email_Select,XDT.Email_Expand,XDT.Email_Filter,XDT.Email_Fixed,XDT.Email_Result,XDT.Email_FormattedResult>;
    Account_Phonecalls: WebMappingRetrieve<XDT.PhoneCall_Select,XDT.PhoneCall_Expand,XDT.PhoneCall_Filter,XDT.PhoneCall_Fixed,XDT.PhoneCall_Result,XDT.PhoneCall_FormattedResult>;
    Account_Tasks: WebMappingRetrieve<XDT.Task_Select,XDT.Task_Expand,XDT.Task_Filter,XDT.Task_Fixed,XDT.Task_Result,XDT.Task_FormattedResult>;
    account_activity_parties: WebMappingRetrieve<XDT.ActivityParty_Select,XDT.ActivityParty_Expand,XDT.ActivityParty_Filter,XDT.ActivityParty_Fixed,XDT.ActivityParty_Result,XDT.ActivityParty_FormattedResult>;
    account_connections1: WebMappingRetrieve<XDT.Connection_Select,XDT.Connection_Expand,XDT.Connection_Filter,XDT.Connection_Fixed,XDT.Connection_Result,XDT.Connection_FormattedResult>;
    account_connections2: WebMappingRetrieve<XDT.Connection_Select,XDT.Connection_Expand,XDT.Connection_Filter,XDT.Connection_Fixed,XDT.Connection_Result,XDT.Connection_FormattedResult>;
    account_master_account: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    account_msys_InternalNotes: WebMappingRetrieve<XDT.msys_InternalNote_Select,XDT.msys_InternalNote_Expand,XDT.msys_InternalNote_Filter,XDT.msys_InternalNote_Fixed,XDT.msys_InternalNote_Result,XDT.msys_InternalNote_FormattedResult>;
    account_parent_account: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    contact_customer_accounts: WebMappingRetrieve<XDT.Contact_Select,XDT.Contact_Expand,XDT.Contact_Filter,XDT.Contact_Fixed,XDT.Contact_Result,XDT.Contact_FormattedResult>;
    msa_account_managingpartner: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    msa_contact_managingpartner: WebMappingRetrieve<XDT.Contact_Select,XDT.Contact_Expand,XDT.Contact_Filter,XDT.Contact_Fixed,XDT.Contact_Result,XDT.Contact_FormattedResult>;
    msys_Account_msys_CommitteeMember_msys_CommitteeMember: WebMappingRetrieve<XDT.msys_CommitteeMember_Select,XDT.msys_CommitteeMember_Expand,XDT.msys_CommitteeMember_Filter,XDT.msys_CommitteeMember_Fixed,XDT.msys_CommitteeMember_Result,XDT.msys_CommitteeMember_FormattedResult>;
    msys_Case_Account_AdditionalParties: WebMappingRetrieve<XDT.msys_Case_Select,XDT.msys_Case_Expand,XDT.msys_Case_Filter,XDT.msys_Case_Fixed,XDT.msys_Case_Result,XDT.msys_Case_FormattedResult>;
    msys_account_AssociationCommitteemembership_account: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    msys_account_TopMainCompany_account: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
    msys_account_msys_arrearscase_656: WebMappingRetrieve<XDT.msys_ArrearsCase_Select,XDT.msys_ArrearsCase_Expand,XDT.msys_ArrearsCase_Filter,XDT.msys_ArrearsCase_Fixed,XDT.msys_ArrearsCase_Result,XDT.msys_ArrearsCase_FormattedResult>;
    msys_account_msys_case: WebMappingRetrieve<XDT.msys_Case_Select,XDT.msys_Case_Expand,XDT.msys_Case_Filter,XDT.msys_Case_Fixed,XDT.msys_Case_Result,XDT.msys_Case_FormattedResult>;
    msys_account_msys_case_primary_party: WebMappingRetrieve<XDT.msys_Case_Select,XDT.msys_Case_Expand,XDT.msys_Case_Filter,XDT.msys_Case_Fixed,XDT.msys_Case_Result,XDT.msys_Case_FormattedResult>;
    msys_account_msys_customerdiscount_51: WebMappingRetrieve<XDT.msys_CustomerDiscount_Select,XDT.msys_CustomerDiscount_Expand,XDT.msys_CustomerDiscount_Filter,XDT.msys_CustomerDiscount_Fixed,XDT.msys_CustomerDiscount_Result,XDT.msys_CustomerDiscount_FormattedResult>;
    msys_account_msys_invoice_928: WebMappingRetrieve<XDT.msys_Invoice_Select,XDT.msys_Invoice_Expand,XDT.msys_Invoice_Filter,XDT.msys_Invoice_Fixed,XDT.msys_Invoice_Result,XDT.msys_Invoice_FormattedResult>;
    msys_account_msys_invoicedivision_313: WebMappingRetrieve<XDT.msys_InvoiceDivision_Select,XDT.msys_InvoiceDivision_Expand,XDT.msys_InvoiceDivision_Filter,XDT.msys_InvoiceDivision_Fixed,XDT.msys_InvoiceDivision_Result,XDT.msys_InvoiceDivision_FormattedResult>;
    msys_account_msys_membership_549: WebMappingRetrieve<XDT.msys_Membership_Select,XDT.msys_Membership_Expand,XDT.msys_Membership_Filter,XDT.msys_Membership_Fixed,XDT.msys_Membership_Result,XDT.msys_Membership_FormattedResult>;
    msys_account_msys_payment_960: WebMappingRetrieve<XDT.msys_Payment_Select,XDT.msys_Payment_Expand,XDT.msys_Payment_Filter,XDT.msys_Payment_Fixed,XDT.msys_Payment_Result,XDT.msys_Payment_FormattedResult>;
    msys_account_msys_paymentmethod_452: WebMappingRetrieve<XDT.msys_PaymentMethod_Select,XDT.msys_PaymentMethod_Expand,XDT.msys_PaymentMethod_Filter,XDT.msys_PaymentMethod_Fixed,XDT.msys_PaymentMethod_Result,XDT.msys_PaymentMethod_FormattedResult>;
    msys_account_msys_selfservicerights_48: WebMappingRetrieve<XDT.msys_SelfServiceRights_Select,XDT.msys_SelfServiceRights_Expand,XDT.msys_SelfServiceRights_Filter,XDT.msys_SelfServiceRights_Fixed,XDT.msys_SelfServiceRights_Result,XDT.msys_SelfServiceRights_FormattedResult>;
    msys_account_msys_taxreport_639: WebMappingRetrieve<XDT.msys_TaxReport_Select,XDT.msys_TaxReport_Expand,XDT.msys_TaxReport_Filter,XDT.msys_TaxReport_Fixed,XDT.msys_TaxReport_Result,XDT.msys_TaxReport_FormattedResult>;
    msys_account_msys_transaction_933: WebMappingRetrieve<XDT.msys_Transaction_Select,XDT.msys_Transaction_Expand,XDT.msys_Transaction_Filter,XDT.msys_Transaction_Fixed,XDT.msys_Transaction_Result,XDT.msys_Transaction_FormattedResult>;
    msys_agreement_Account_account: WebMappingRetrieve<XDT.msys_Agreement_Select,XDT.msys_Agreement_Expand,XDT.msys_Agreement_Filter,XDT.msys_Agreement_Fixed,XDT.msys_Agreement_Result,XDT.msys_Agreement_FormattedResult>;
    msys_agreementconnection_Account_account: WebMappingRetrieve<XDT.msys_AgreementConnection_Select,XDT.msys_AgreementConnection_Expand,XDT.msys_AgreementConnection_Filter,XDT.msys_AgreementConnection_Fixed,XDT.msys_AgreementConnection_Result,XDT.msys_AgreementConnection_FormattedResult>;
    msys_committee_AccountUnion_account: WebMappingRetrieve<XDT.msys_Committee_Select,XDT.msys_Committee_Expand,XDT.msys_Committee_Filter,XDT.msys_Committee_Fixed,XDT.msys_Committee_Result,XDT.msys_Committee_FormattedResult>;
    msys_committeemember_AccountAppointedBy_account: WebMappingRetrieve<XDT.msys_CommitteeMember_Select,XDT.msys_CommitteeMember_Expand,XDT.msys_CommitteeMember_Filter,XDT.msys_CommitteeMember_Fixed,XDT.msys_CommitteeMember_Result,XDT.msys_CommitteeMember_FormattedResult>;
    msys_configuration_MainUnion_account: WebMappingRetrieve<XDT.msys_Configuration_Select,XDT.msys_Configuration_Expand,XDT.msys_Configuration_Filter,XDT.msys_Configuration_Fixed,XDT.msys_Configuration_Result,XDT.msys_Configuration_FormattedResult>;
    msys_contact_PrimaryWorkplace_account: WebMappingRetrieve<XDT.Contact_Select,XDT.Contact_Expand,XDT.Contact_Filter,XDT.Contact_Fixed,XDT.Contact_Result,XDT.Contact_FormattedResult>;
    msys_contact_SecondaryUnion_account: WebMappingRetrieve<XDT.Contact_Select,XDT.Contact_Expand,XDT.Contact_Filter,XDT.Contact_Fixed,XDT.Contact_Result,XDT.Contact_FormattedResult>;
    msys_debitorsettlement_Account_account: WebMappingRetrieve<XDT.msys_DebitorSettlement_Select,XDT.msys_DebitorSettlement_Expand,XDT.msys_DebitorSettlement_Filter,XDT.msys_DebitorSettlement_Fixed,XDT.msys_DebitorSettlement_Result,XDT.msys_DebitorSettlement_FormattedResult>;
    msys_education_PlaceOfEducation_account: WebMappingRetrieve<XDT.msys_Education_Select,XDT.msys_Education_Expand,XDT.msys_Education_Filter,XDT.msys_Education_Fixed,XDT.msys_Education_Result,XDT.msys_Education_FormattedResult>;
    msys_educationtype_PlaceOfStudy_account: WebMappingRetrieve<XDT.msys_EducationType_Select,XDT.msys_EducationType_Expand,XDT.msys_EducationType_Filter,XDT.msys_EducationType_Fixed,XDT.msys_EducationType_Result,XDT.msys_EducationType_FormattedResult>;
    msys_employment_Workplace_account: WebMappingRetrieve<XDT.msys_Employment_Select,XDT.msys_Employment_Expand,XDT.msys_Employment_Filter,XDT.msys_Employment_Fixed,XDT.msys_Employment_Result,XDT.msys_Employment_FormattedResult>;
    msys_event_Organizer_account: WebMappingRetrieve<XDT.msys_Event_Select,XDT.msys_Event_Expand,XDT.msys_Event_Filter,XDT.msys_Event_Fixed,XDT.msys_Event_Result,XDT.msys_Event_FormattedResult>;
    msys_event_Venue_account: WebMappingRetrieve<XDT.msys_Event_Select,XDT.msys_Event_Expand,XDT.msys_Event_Filter,XDT.msys_Event_Fixed,XDT.msys_Event_Result,XDT.msys_Event_FormattedResult>;
    msys_financetype_Account_account: WebMappingRetrieve<XDT.msys_Financetype_Select,XDT.msys_Financetype_Expand,XDT.msys_Financetype_Filter,XDT.msys_Financetype_Fixed,XDT.msys_Financetype_Result,XDT.msys_Financetype_FormattedResult>;
    msys_msys_answer_account_msys_DynamicListAnswer: WebMappingRetrieve<XDT.msys_Answer_Select,XDT.msys_Answer_Expand,XDT.msys_Answer_Filter,XDT.msys_Answer_Fixed,XDT.msys_Answer_Result,XDT.msys_Answer_FormattedResult>;
    msys_msys_emailtemplate_account_msys_ValidationEntity: WebMappingRetrieve<XDT.msys_EmailTemplate_Select,XDT.msys_EmailTemplate_Expand,XDT.msys_EmailTemplate_Filter,XDT.msys_EmailTemplate_Fixed,XDT.msys_EmailTemplate_Result,XDT.msys_EmailTemplate_FormattedResult>;
    msys_paymentmethod_PayrollAt_account: WebMappingRetrieve<XDT.msys_PaymentMethod_Select,XDT.msys_PaymentMethod_Expand,XDT.msys_PaymentMethod_Filter,XDT.msys_PaymentMethod_Fixed,XDT.msys_PaymentMethod_Result,XDT.msys_PaymentMethod_FormattedResult>;
    msys_payrollrun_Account_account: WebMappingRetrieve<XDT.msys_PayrollRun_Select,XDT.msys_PayrollRun_Expand,XDT.msys_PayrollRun_Filter,XDT.msys_PayrollRun_Fixed,XDT.msys_PayrollRun_Result,XDT.msys_PayrollRun_FormattedResult>;
    msys_placementrule_Account_account: WebMappingRetrieve<XDT.msys_PlacementRule_Select,XDT.msys_PlacementRule_Expand,XDT.msys_PlacementRule_Filter,XDT.msys_PlacementRule_Fixed,XDT.msys_PlacementRule_Result,XDT.msys_PlacementRule_FormattedResult>;
    msys_product_Related_Account_account: WebMappingRetrieve<XDT.msys_Product_Select,XDT.msys_Product_Expand,XDT.msys_Product_Filter,XDT.msys_Product_Fixed,XDT.msys_Product_Result,XDT.msys_Product_FormattedResult>;
    msys_registration_CompanyPayer_account: WebMappingRetrieve<XDT.msys_Registration_Select,XDT.msys_Registration_Expand,XDT.msys_Registration_Filter,XDT.msys_Registration_Fixed,XDT.msys_Registration_Result,XDT.msys_Registration_FormattedResult>;
    msys_team_SubUnion_account: WebMappingRetrieve<XDT.Team_Select,XDT.Team_Expand,XDT.Team_Filter,XDT.Team_Fixed,XDT.Team_Result,XDT.Team_FormattedResult>;
    msys_team_TopLevelWorkplace_account: WebMappingRetrieve<XDT.Team_Select,XDT.Team_Expand,XDT.Team_Filter,XDT.Team_Fixed,XDT.Team_Result,XDT.Team_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  accounts: WebMappingRetrieve<XDT.Account_Select,XDT.Account_Expand,XDT.Account_Filter,XDT.Account_Fixed,XDT.Account_Result,XDT.Account_FormattedResult>;
}
interface WebEntitiesRelated {
  accounts: WebMappingRelated<XDT.Account_RelatedOne,XDT.Account_RelatedMany>;
}
interface WebEntitiesCUDA {
  accounts: WebMappingCUDA<XDT.Account_Create,XDT.Account_Update,XDT.Account_Select>;
}
