// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("XrmDefinitelyTyped")>]
[<assembly: AssemblyProductAttribute("XrmDefinitelyTyped")>]
[<assembly: AssemblyDescriptionAttribute("Tool to generate TypeScript declaration files for MS CRM Dynamics client-side coding.")>]
[<assembly: AssemblyCompanyAttribute("Delegate A/S")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (c) Delegate A/S 2015")>]
[<assembly: AssemblyVersionAttribute("2.0.1")>]
[<assembly: AssemblyFileVersionAttribute("2.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "XrmDefinitelyTyped"
    let [<Literal>] AssemblyProduct = "XrmDefinitelyTyped"
    let [<Literal>] AssemblyDescription = "Tool to generate TypeScript declaration files for MS CRM Dynamics client-side coding."
    let [<Literal>] AssemblyCompany = "Delegate A/S"
    let [<Literal>] AssemblyCopyright = "Copyright (c) Delegate A/S 2015"
    let [<Literal>] AssemblyVersion = "2.0.1"
    let [<Literal>] AssemblyFileVersion = "2.0.1"
