// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("XrmDefinitelyTyped")>]
[<assembly: AssemblyProductAttribute("XrmDefinitelyTyped")>]
[<assembly: AssemblyDescriptionAttribute("Tool to generate TypeScript declaration files for MS Dynamics 365/CRM client-side coding.")>]
[<assembly: AssemblyCompanyAttribute("Delegate A/S")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (c) Delegate A/S 2017")>]
[<assembly: AssemblyVersionAttribute("3.0.2")>]
[<assembly: AssemblyFileVersionAttribute("3.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "XrmDefinitelyTyped"
    let [<Literal>] AssemblyProduct = "XrmDefinitelyTyped"
    let [<Literal>] AssemblyDescription = "Tool to generate TypeScript declaration files for MS Dynamics 365/CRM client-side coding."
    let [<Literal>] AssemblyCompany = "Delegate A/S"
    let [<Literal>] AssemblyCopyright = "Copyright (c) Delegate A/S 2017"
    let [<Literal>] AssemblyVersion = "3.0.2"
    let [<Literal>] AssemblyFileVersion = "3.0.2"
